### ISSUE TITLE
Line space is not adjusted after changing font size using CodeArea.setStyle().

### ISSUE THREAD

**Issue by janghyunq** [TomasMikula/RichTextFX#100]
For example when the font size is changed from 20 to 10 using

     CodeArea.setStyle("-fx-font-size:10;");

the line space is not adjusted automatically. It seems that it retains the former line space. Manual resizing the window corrects the problem.
Is there any way to an 'invalidate()' method to force repaint the entire CodeArea?

video clip:
http://www.youtube.com/watch?v=4-oKqV86uB8&feature=youtu.be

**Comment by TomasMikula** [comment]
This is fixed in version 0.6. I added [a demo](https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/FontSizeSwitcher.java). Quite interestingly, `-fx-font-size` also affects the size of the scrollbar.
