### ISSUE TITLE
Missing. import org.reactfx.InterceptableEventStream;

### ISSUE THREAD

**Issue by melkhaldi** [TomasMikula/RichTextFX#109]
Hi Tomas, I tried to load the new 0.6 release to check out the update and report issues, It seems that you something is changed in the reactFX. Is that correct? If so, what do I change in the code below to make it work again? I have some code like this:

    InterceptableEventStream<PlainTextChange> changes = this.richTextArea.plainTextChanges().interceptable();
            changes.muteWhile(() -> {
                this.richTextArea.insertText(this.richTextArea.getCaretPosition(), txt);
            });

Thanks,
Maher

**Comment by TomasMikula** [comment]
Hi Maher, you are right, there have been many changes in ReactFX. You can change your code to:

```java
SuspendableEventStream<PlainTextChange> changes = this.richTextArea.plainTextChanges().suppressible();
changes.suspendWhile(() -> {
    this.richTextArea.insertText(this.richTextArea.getCaretPosition(), txt);
});
```

Thanks for early testing! ;)

**Comment by melkhaldi** [comment]
Works, found an issue. will report on another thread.
