### ISSUE TITLE
Copy/Paste Exception

### ISSUE THREAD

**Issue by RobertBColton** [TomasMikula/RichTextFX#111]
I pulled the new 0.6 release to see if #88 was gone and it certainly is but there seems to be a new issue with the demo.
![0.6 No Artifacts](https://cloud.githubusercontent.com/assets/3212801/6102626/07b631c2-b008-11e4-90a6-75d74c3479de.png)

Whenever I just run the demo using the default command in the repo's readme.md I can reproduce a new issue each time I run. When it opens select all the text and copy it to the clipboard, then keep pasting it. The new pastes will not be syntax highlighted properly and after so many pastes exceptions will start pouring out in the console for like a split second.

**Comment by TomasMikula** [comment]
This was a problem with the demo, name the regular expression for String literals. However, I have no idea why it threw a StackOverflowError.

**Comment by TomasMikula** [comment]
I re-uplaoded the [demos jar](https://github.com/TomasMikula/RichTextFX/releases/download/v0.6/richtextfx-demos-fat-0.6.jar).

**Comment by RobertBColton** [comment]
@TomasMikula Excellent, working great and selection artifacts seem mainly gone! Great work, and I look forward to using this in my own project now.
