### ISSUE TITLE
With tabs, only one tab shows text

### ISSUE THREAD

**Issue by cranphin** [TomasMikula/RichTextFX#113]
Hi! Me again :)

It seems when I fill two tabs with a CodeArea and a lot of text (might have to be atleast a screen full??), the content of one of the two won't show.

See the following example.
Note: If you switch to the tab which isn't showing content, and then resize the window, it suddenly displays. But then the content of the other tab dissapears! :)

```java
import java.io.IOException;
import java.security.SecureRandom;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Tab;
import javafx.scene.control.TabPane;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import org.fxmisc.richtext.CodeArea;

public class TestSample extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws IOException, InterruptedException {

        // Create some test data.
        final StringBuilder builder = new StringBuilder();
        final SecureRandom random = new SecureRandom();
        for (int line = 0; line < 24 * 5; line++) {
            for (int charPos = 0; charPos < 80; charPos++) {
                builder.append((char) ('A' + random.nextInt('Z' - 'A')));
            }
            builder.append("\n");
        }
        final String testData = builder.toString();

        // Setup the scene
        final CodeArea codeArea1 = new CodeArea();
        final Tab tab1 = new Tab("Tab1");
        tab1.setContent(codeArea1);

        final CodeArea codeArea2 = new CodeArea();
        final Tab tab2 = new Tab("Tab2");
        tab2.setContent(codeArea2);

        TabPane tabPane = new TabPane();
        tabPane.getTabs().add(tab1);
        tabPane.getTabs().add(tab2);

        final Scene scene = new Scene(new StackPane(tabPane), 600, 400);
        primaryStage.setScene(scene);
        primaryStage.show();

        // Add the test data
        codeArea1.appendText(testData);
        codeArea2.appendText(testData);
    }
}
```

**Comment by cranphin** [comment]
Oh! versions:
jdk1.8.0_25 (64 bit)
org.fxmisc.richtext:richtextfx:0.6

**Comment by TomasMikula** [comment]
Thanks for the sample code. I can reproduce this with JDK8u20. The problem no longer appears with JDK8u40-b23.

**Comment by JordanMartinez** [comment]
I believe this was the same problem I encountered in my issue (#123). I'm currently using JDK8u31-b13 on Linux, so I'm not sure how to get the early release since mine is installed by PPA.

**Comment by TomasMikula** [comment]
You can just [download](https://jdk8.java.net/download.html) the tar file, unpack and add the `bin` subdirectory to the _front_ of your `PATH` (to take precedence over the installed java).

In Eclipse, you can add a new JDK under _Preferences -> Java -> Installed JREs -> Add -> Standard VM_

**Comment by JordanMartinez** [comment]
Sorry for responding so late. School just started up recently.

Thank you for the info! I'll try it soon.

**Comment by TomasMikula** [comment]
Also, JDK 8u40 was officially released this week.

**Comment by cranphin** [comment]
Yup, official JDK 8u40 fixes it for me :)
