### ISSUE TITLE
Flickering  in 0.6.1

### ISSUE THREAD

**Issue by melkhaldi** [TomasMikula/RichTextFX#115]
Hi Tomas, The new 0.6.1 release introduced flickering when making changes to the text area. Running Java U40 b23.
 Best,
Maher

**Comment by TomasMikula** [comment]
I released 0.6.2 where this is fixed. It was kinda stupid regression, where I forgot to uncomment the code that applied CSS to the line, which I commented out for some experimenting. What was happening was that the line was laid out without CSS applied, and right after that CSS was applied and the line was laid out again to take the CSS into account.

**Comment by melkhaldi** [comment]
Confirmed.
