### ISSUE TITLE
Support selection by dragging mouse outside view port

### ISSUE THREAD

**Issue by melkhaldi** [TomasMikula/RichTextFX#116]
Can you add support for selecting text by dragging the mouse outside of the view port? Similar to what is being supported in various text editing tools.

**Comment by RobertBColton** [comment]
@TomasMikula I would like to add that I've tested the latest release 6.2 and see no new issues and can confirm the text artifacts are still fixed. I would also like this feature here.

**Comment by TomasMikula** [comment]
I will note also here that a workaround is to start the selection in the viewport and scroll the mouse wheel while the mouse button is still pressed.

**Comment by TomasMikula** [comment]
This is now supported in 0.6.3.

**Comment by melkhaldi** [comment]
Works!

**Comment by RobertBColton** [comment]
Working great here as well! Very smooth and works great horizontally or vertically!
