### ISSUE TITLE
setStyle() to define selection background color broken.

### ISSUE THREAD

**Issue by melkhaldi** [TomasMikula/RichTextFX#117]
Hi 
Tomas, can you try this on Code Area of Text Area:

setStyle("-fx-highlight-fill: gold;");
It used to work and it defaults to  the blue background for text selection.

Can you reproduce this?
Thanks,
Maher

**Comment by TomasMikula** [comment]
Thanks, I fixed it and re-uploaded the jars.

**Comment by melkhaldi** [comment]
fix confirmed!
