### ISSUE TITLE
Breaking changes in 0.6.2

### ISSUE THREAD

**Issue by jntrb** [TomasMikula/RichTextFX#118]
While upgrading from 0.5.1 to 0.6.2 I found some breaking changes.

Code area
---

Setting line numbers in 0.5.1:

    codeArea.setParagraphGraphicFactory(LineNumberFactory.get(codeArea, format, stylesheet));

In 0.6.2 there is no stylesheet parameter any more:

    codeArea.setParagraphGraphicFactory(LineNumberFactory.get(codeArea, format));

Instead, use `.lineno { ... }` CSS in the stylesheet applied to the code area.

**Comment by TomasMikula** [comment]
Yes, you are right. The default style of line numbers is now set by setting the properties in Java code. Therefore, it has low priority, so it can be easily overridden in the stylesheet of the Scene or any other parent.
