### ISSUE TITLE
StyleClassedTextArea consumes too much memory

### ISSUE THREAD

**Issue by hrzafer** [TomasMikula/RichTextFX#119]
I read a 3 MB text file put its content to my StyleClassedTextArea object with the following code:

byte[] bytes = Files.readAllBytes(file.toPath());
String str = new String(bytes, "UTF-8");
area.setStyleClass(0, area.getLength(), UNKNOWN);
area.replaceText(0, area.getLength(), str);

My program stucks and on the tast manager memory usage starts to increase from 180 MB to something around 4GB.

Am I doing something wrong?

**Comment by TomasMikula** [comment]
What version of RichTextFX are you using?

**Comment by TomasMikula** [comment]
If you experience this problem in 0.6.2, please re-open this issue and include a minimal reproducible example.

**Comment by hrzafer** [comment]
I was using version 0.6. Now I updated my pom.xml and it works OK.
