### ISSUE TITLE
Text rendering artifacts when window size is changed

### ISSUE THREAD

**Issue by hrzafer** [TomasMikula/RichTextFX#120]
I just run ManualHighlighting.java from your repo with the following style:

    .red {
        -fx-font-size: 12pt;
        -fx-fill: rgb(180, 32, 33);
        -fx-font-family: "Courier New";
     
    }

![capture](https://cloud.githubusercontent.com/assets/4048197/6367201/7d98e8f8-bcd8-11e4-93f0-e34a74cb2763.PNG)

When I resize the window, this is what happens:

![capture](https://cloud.githubusercontent.com/assets/4048197/6367226/e329f61c-bcd8-11e4-859d-19a50b64cfad.PNG)

**Comment by TomasMikula** [comment]
I can reproduce this using JDK 8u40-b02 or older, but not 8u40-b20 or newer. So it seems like a JavaFX problem that has been fixed. What JDK/JRE version are you using?

**Comment by hrzafer** [comment]
JDK 8u31. Isn't it the latest stable release? How can I obtain 8u40-b20 or newer?

**Comment by TomasMikula** [comment]
Yes, that is the latest stable release. There are, however, early access builds of 8u40 available: https://jdk8.java.net/download.html

**Comment by hrzafer** [comment]
I also tested with 8u40-b23 and it seems the problem is solved for 8u40-b20 or newer. Thanks.
