### ISSUE TITLE
Scroll direction (Up/Down)

### ISSUE THREAD

**Issue by melkhaldi** [TomasMikula/RichTextFX#122]
Hi Tomas,
In 0.6.3 Scrolling now works in the inverse direction to what is set in the OS. Can you verify on your end?
I am using Windows 7 u40b23.

**Comment by TomasMikula** [comment]
Ha! Yes :)

**Comment by melkhaldi** [comment]
:D

**Comment by TomasMikula** [comment]
Try again ;)

**Comment by melkhaldi** [comment]
Yep, now works as expected!
