### ISSUE TITLE
Can't set Font of StyleClassedTextArea

### ISSUE THREAD

**Issue by Emrage** [TomasMikula/RichTextFX#125]
Hello i'm doing this:

		area.setFont(Font.font(20));

But nothing happens the font stays the same.

This is my StyleClassesTextArea:

	private StyleClassedTextArea area = new StyleClassedTextArea();

And i'm called the setFont method in the start method above stage.show();

**Comment by TomasMikula** [comment]
Hi, use this instead:

```java
area.setStyle("-fx-font-size: 20;");
```

Maybe I should just remove `fontProperty` on text area altogether.

**Comment by JordanMartinez** [comment]
I just created a branch to remove this. However, if the skin is going to be removed (#206), would it actually be worth it to keep the `fontProperty`?

**Comment by TomasMikula** [comment]
Removing the skin doesn't make much difference here. Propagating the `font

**Comment by JordanMartinez** [comment]
I believe this issue can be closed now.

**Comment by TomasMikula** [comment]
Yes, thank you.
