### ISSUE TITLE
Noticeable Input Latency -- can something be done ? 

### ISSUE THREAD

**Issue by hsyed** [TomasMikula/RichTextFX#126]
There is a noticeable latency with JavaFX across the board in general. (Dragging nodes, animation etc etc) when compared to other frameworks / render technologies. This latency is not noticeable for the average user but for someone working with a lot of text this will be a major annoyance.

I noticed it when I was playing with the rich text demo. Can any micro-optimizations be done to make the experience rival for example this very text box that I am typing in ? (Safari, Macbook, 10.10).

I know it is possible in swing because of the lengths Jetbrains have gone to make a first-class editing experience. The UI is much more responsive than Eclipse (which I know is not Swing). It *almost* rivals this text box

**Comment by TomasMikula** [comment]
Hi Hassan, such a question is very general for me to answer. If you can point out a concrete operation that you perceive as slow and provide detailed instructions how to reproduce it, then I can have a look and try to answer your question.
