### ISSUE TITLE
Two problems positioning popup relative to caret

### ISSUE THREAD

**Issue by gerdwagner** [TomasMikula/RichTextFX#128]
1. The positioning does not work right after the editors text was changed by calling
StyledTextArea.replaceText(int start, int end, String text)
and the caret was moved by the change. (A typically use case that does so is code completion). 
After the next user edit positioning works alright again.

2.  With an initially opened and focused editor positioning the popup at the caret  bottom (PopupAlignment.CARET_BOTTOM) does not work. It shows up somewhere in the upper half of the caret.

Reproduction:
Both problems can be seen in the SQuirreL SQL FX snapshot 20150313_1200 which is based on RichTextFX 0.6.3, see
http://sourceforge.net/projects/squirrel-sql/files/sqfx/squirrelsqlfx-snapshot-20150313_1200.zip/download

In the SQL editor use the code completion short cut (ctrl+space) to display the code completion popup.

**Comment by TomasMikula** [comment]
Hi, I tried to implement both cases you describe in my PopupDemo example, but I cannot reproduce these issues. Can you provide a minimal self-contained example that reproduces these issues?

**Comment by gerdwagner** [comment]
Below's the code to reproduce the scond problem. Just hit ctrl+space after start.
I'll try to find a similar easy way to reproduce the first.

```java
package pack;

import javafx.application.Application;
import javafx.geometry.Point2D;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyCodeCombination;
import javafx.scene.input.KeyEvent;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.stage.Popup;
import javafx.stage.Stage;
import org.fxmisc.richtext.CodeArea;
import org.fxmisc.richtext.InlineCssTextArea;
import org.fxmisc.richtext.PopupAlignment;

public class PopupDemo extends Application
{

   public static void main(String[] args)
   {
      launch(args);
   }

   @Override
   public void start(Stage primaryStage)
   {
      CodeArea area = new CodeArea();
      area.setWrapText(true);

      VBox.setVgrow(area, Priority.ALWAYS);

      Popup popup = new Popup();
      Button btn = new Button("I am a popup button!");
      popup.getContent().add(btn);
      area.setPopupWindow(popup);


      primaryStage.setScene(new Scene(new VBox(area), 300, 300));
      primaryStage.setTitle("Popup Demo");
      primaryStage.show();

      area.setOnKeyPressed(e -> onHandleKeyEvent(e, area, popup, primaryStage));
   }

   private void onHandleKeyEvent(KeyEvent keyEvent, CodeArea area, Popup popup, Stage primaryStage)
   {

      if (new KeyCodeCombination(KeyCode.SPACE, KeyCodeCombination.CONTROL_DOWN).match(keyEvent))
      {
         area.setPopupAlignment(PopupAlignment.CARET_BOTTOM);
         popup.show(primaryStage);
      }
   }
}

**Comment by TomasMikula** [comment]
Hi Gerd. The problem is that the popup window is repositioned only when the caret moves, not when `popupAlignment` property is set. This is certainly an issue, but the workaround is to set popup alignment just once with the popup window and not in every time in the key handler:

    area.setPopupWindow(popup);
    area.setPopupAlignment(PopupAlignment.CARET_BOTTOM);

In the key handler, you then only need to call `show`.

**Comment by gerdwagner** [comment]
Hi Thomas,

thank you for the workaround. 

Here is a bit of a refinement of the workaround for people who can only decide on the popup's anchor offset or alignment right when the popup is opened:

Simply move and move back the caret from within the code that opens the popup. The code for this may be:

      int caretPosition = _codeArea.getCaretPosition();

      if(0 != caretPosition)
      {
         _codeArea.positionCaret(caretPosition - 1);
         _codeArea.positionCaret(caretPosition);
      }
      else
      {
         _codeArea.positionCaret(caretPosition + 1);
         _codeArea.positionCaret(caretPosition);
      }

A usual example where one can only decide on the popup's anchor offset when it is opened is code completion.

Note:
This is a workaround for both of the problems mentioned in this issue.
