### ISSUE TITLE
Vertical movement of the caret doesn't work when we use Collections.emptyList() as separator between words

### ISSUE THREAD

**Issue by cementovoz** [TomasMikula/RichTextFX#131]
How to reproduce : 
1 Open example as java -cp richtextfx-demos-fat-0.6.3.jar org.fxmisc.richtext.demo.JavaKeywords
2 set caret to end of source (after RBRACE)
3 press and release up key in your keyboard - you will see that caret doesn't move to up line.
4 you may try again previous step - caret doesn't move to up

**Comment by TomasMikula** [comment]
Hi, I cannot reproduce this issue. Have you modified the source code, or do you experience the issue with the jar file downloaded from this site?

**Comment by cementovoz** [comment]
Hi, no, i can't modified source, jar was downloaded from https://github.com/TomasMikula/RichTextFX/releases/download/v0.6.3/richtextfx-demos-fat-0.6.3.jar
hm, okey, I found trouble - this issue can't reproduced with jdk8u40 b27, but reproduced with jdk8 b132,  jdk8u31, jdk9.

**Comment by TomasMikula** [comment]
8u40 is the recommended version, since it fixes some problems. I haven't yet tested early access builds of JDK 9.
