### ISSUE TITLE
Calculating height of a paragraph (for the purpose of computing page size for printing)

### ISSUE THREAD

**Issue by djskrien** [TomasMikula/RichTextFX#132]
I'd like to be able to print the contents of a CodeArea that contains a hundred or more lines of code, which means I need to break it up into pages for printing.  Each line of my code is one Paragraph.  Therefore, using PageLayout.getPrintableHeight() to get the total number of points I have to work with on each page, and dividing that total by the number of points of height per paragraph, I can figure out how many paragraphs will fit on a page.  But to do this, I need a way of getting the height of a paragraph.  Is there a way to do it, given the font and font size of the paragraph, e.g., Courier 12?  Or is there some other better way of breaking a CodeArea into pages for printing?  (Also, should I have asked this question on StackOverflow instead of here?)

**Comment by TomasMikula** [comment]
There isn't any support for breaking text into pages.

To calculate the height of text given the font, you could create a [Text](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/text/Text.html) or [TextFlow](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/text/TextFlow.html) node, set the font, and get its preferred height. You could also try to look into `Text` how it computes its size, if you want to be able to compute the size based on just the font.

You could also dig into into CodeArea to get the [VirtualFlow](http://www.fxmisc.org/flowless/javadoc/org/fxmisc/flowless/VirtualFlow.html). Resize the CodeArea to the printable size and then scroll to the top (e.g. `codeArea.moveTo(0)`) and get the number of visible paragraphs as `virtualFlow.visibleCells().size()`. Note that the last visible cell may not be fully visible, however.

Or, also using the enclosed VirtualFlow, to get the height of the first visible paragraph, you could just do `virtualFlow.visibleCells().get(0).getLayoutBounds().getHeight()`.

**Comment by djskrien** [comment]
Thanks for the prompt response.  I tried creating both a Text and a TextFlow node using my font and font size and then asking for its height, but it gave me the wrong height as far as printing is concerned.  I'd like to try your VirtualFlow idea to get the height of the first visible paragraph, but can you give me a little more information on how to get a virtual flow from the CodeArea?

**Comment by TomasMikula** [comment]
You probably also need to set some text for the `Text` or `TextFlow`, and maybe even add it to the scene graph, not sure.

Getting the VirtualFlow is not public API, so be advised that this may change in the future. Currently, it happens to be the first child of the first child of the CodeArea, so this is the direct way to get it:

```java
VirtualFlow<?, ?> vf = (VirtualFlow<?, ?>)
        ((Parent) codeArea.getChildrenUnmodifiable().get(0))
                .getChildrenUnmodifiable().get(0);
```

A _little_ more robust way is to look it up by its style class:

```java
VirtualFlow<?, ?> vf = (VirtualFlow<?, ?>) codeArea.lookup(".virtual-flow");
```

Then,

```java
double height = vf.visibleCells().get(0).getNode().getLayoutBounds().getHeight();
```

**Comment by djskrien** [comment]
Thank you!  The last way works great.
