### ISSUE TITLE
Spacebar scrolls the scrollpane

### ISSUE THREAD

**Issue by IMurdocI** [TomasMikula/RichTextFX#134]
Hello,

I'm using the the CodeEditor as an editabele object on Pane that is inside a scrollpane. (see it like a TextField in MS Word).

I have the issue, that when pressing the spacebar inside the CodeEditor, my Scrollpane scrolls down, without me adding any code that may change the vvalue of the scrollpane!

**Comment by TomasMikula** [comment]
Hi! Does it also add a space to the editor or not?

**Comment by IMurdocI** [comment]
hey,
Yes, space is also added to the Editor!

**Comment by TomasMikula** [comment]
Thanks. Scroll by spacebar is probably the desired behavior of the ScrollPane. The problem probably is that the event is not consumed by the CodeArea. There are a two events fired when a character key is pressed: KEY_PRESSED and KEY_TYPED. CodeArea handles the KEY_TYPED event and inserts a space character, but does not handle the KEY_PRESSED event, so it propagates up and is handled by the ScrollPane as a command to scroll down. This is an interesting problem that questions the design of key handling in JavaFX.

Luckily for you, there is a simple workaround: you can add an event handler to CodeArea that consumes the KEY_PRESSED event for space:

```java
codeArea.addEventHandler(KeyEvent.KEY_PRESSED, event -> {
    if(event.getCode() == KeyCode.SPACE) {
        event.consume();
    }
});
```

**Comment by IMurdocI** [comment]
great, thank you very much for the help. 
Should have thought of the event.consume myself.

**Comment by TomasMikula** [comment]
Seems like I can solve this in RichTextFX, by checking whether a KEY_PRESSED event [isLetterKey()](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/input/KeyCode.html#isLetterKey--) or [isWhitespaceKey()](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/input/KeyCode.html#isWhitespaceKey--) and only consume it in that case, otherwise let it bubble up. I will leave this open so that I don't forget about it.

**Comment by TomasMikula** [comment]
I'm not sure whether that will work for characters like `.,:;+-=_(){}[]\/?!@#$%^&*~`, but should be useful anyway.

**Comment by IMurdocI** [comment]
by just consuming the event only when spacebar is pressed (as you mentioned in your second post) everything works fine, all characters and whitespaces (space/tab)!

**Comment by TomasMikula** [comment]
Thanks for confirming.

It is not a general solution, though, because the problem would re-appear for someone who puts a CodeArea as a child of a node that, for example, uses `KEY_PRESSED` handler on `Z` or any other character. CodeArea handles `KEY_TYPED` for `Z`, but not `KEY_PRESSED` for `Z`.

**Comment by TomasMikula** [comment]
My proposed more general solution would work for letters (A-Z), digits (0-9) and whitespace characters, but not for other special characters as mentioned above.

**Comment by IMurdocI** [comment]
okay, seems like a good start solution!

**Comment by TomasMikula** [comment]
I [asked](http://mail.openjdk.java.net/pipermail/openjfx-dev/2015-April/016980.html) about a general solution on the JavaFX mailing list, with no answer so far, so I proceeded with a fix the way I proposed above.
