### ISSUE TITLE
Syntax highlighting disappears if you copy some code and immediately paste it back

### ISSUE THREAD

**Issue by djskrien** [TomasMikula/RichTextFX#135]
Run the Java Keywords Demo.  Select some of the text, type Ctrl-C to copy the selected text, and then type Ctrl-V to paste all the selected text back over itself.  The syntax highlighting disappears for the pasted text.

**Comment by melkhaldi** [comment]
Would it get highlighted again after if you make any other key entry, space
for example? I think maybe the update does not listen to copy paste event,
only key entry.

**Comment by djskrien** [comment]
Yes, if you make another key entry after pasting, the highlighting reappears.  In fact, the highlighting reappears even after pasting as long as you are not pasting back exactly the same code that is already there.  This suggests that the highlighting is done by a ChangeListener of the textProperty of the CodeArea.  Unfortunately, the ChangeListener does nothing if the old text matches the new text.

**Comment by TomasMikula** [comment]
Good catch! Syntax highlighting is listening to (plain) text changes, and in this case, the text content does not change. Combined with the fact that Copy&Paste does not preserve styling, you get a change in style which is not detected by the parser.

**Comment by djskrien** [comment]
Is there an easy fix for this problem?

**Comment by TomasMikula** [comment]
Yes, you can observe `richChanges()` and trigger highlighting from there:

```java
codeArea.richChanges().subscribe(change -> {
    codeArea.setStyleSpans(0, computeHighlighting(codeArea.getText()));
});
```

**Comment by djskrien** [comment]
I'm missing something.  I replaced the code on lines 78-80 in JavaKeywords.java:
```java
codeArea.textProperty().addListener((obs, oldText, newText) -> {
    codeArea.setStyleSpans(0, computeHighlighting(newText));
});
```
with the code you gave above:
```java
codeArea.richChanges().subscribe(change -> {
    codeArea.setStyleSpans(0, computeHighlighting(codeArea.getText()));
});
```
and tried to run it, but got infinite recursion.

**Comment by TomasMikula** [comment]
You're not missing anything, it is a bug. `richChanges()` keeps reporting a change event if `setStyleSpans` did not result in an actual change. In the meantime, use an invalidation listener on `textProperty`. It gets invalidated even if there is no change in the end, so it will work to eliminate the original problem:

```java
codeArea.textProperty().addListener(obs -> {
    codeArea.setStyleSpans(0, computeHighlighting(codeArea.getText()));
});
```
