### ISSUE TITLE
Suggestion: controlling the behavior of caret position and Inserted (or removed) characters. 

### ISSUE THREAD

**Issue by melkhaldi** [TomasMikula/RichTextFX#137]
Hi Tomas,
Is it possible to define some sort of [behavior?] model for entering text (not sure I am using the correct terminology here).

Currently, the standard behavior in OS are:
-Delete : removes characters ahead of the caret while keeping the caret in place.
-Backspace: removes characters before caret and moves caret backward.

I would like to define a behavior for the text changes (insertion or removal) in terms of: 
-where it is inserted/removed character are relative to the caret (before or after),  and in case of insertion, is it inserted or is it replacing what is in place.
-where does the caret go after. (go back, remain in-place, or move forward).

I am thinking of a few ways to experiment with text entry and was wondering if such behaviors can be exposed. 

An example use:
TextBefore 'TextToChange' TextAfter

If I want to change 'TextToChange', I typically delete it, or select the range and start typing, which also deletes it. 

Instead, I would like to be able to select the range, and start typing within the range. So two cases here:
-if new entered text is longer, it would push 'TextAfter' forward.
-if it is less, upon some key combination (maybe CTRL+ENTER), I would get the new inserted text in, remove the residue (from old selection), and pull back the 'TextAfter'.

I can think of ways to do this with listening to keys, but thought maybe there is a smart way to implement this in the infrastructure of RichTextFX by controlling behavior of text entry (I realize this is so not standard--but that is what experimentation is for! :) )
 
Best,
Maher

**Comment by TomasMikula** [comment]
Hi Maher. `StyledTextArea` itself implements a very limited set of basic operations, like `replace(from, to, replacement)` or `selectRange(from, to)`. Other operations, e.g. from the [EditActions](http://www.fxmisc.org/richtext/javadoc/org/fxmisc/richtext/EditActions.html) interface, are then implemented on top of the basic methods. On top of all that is then [StyledTextAreaBehavior](https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/skin/StyledTextAreaBehavior.java), which implements keyboard input. I suggest you look there. Let me know if you need help overriding the default event handlers.

**Comment by melkhaldi** [comment]
Thanks, Tomas. I'll take a look and wrap my head around this then get back to you! 
Best,
Maher
