### ISSUE TITLE
RichTextFX support multiple selection?

### ISSUE THREAD

**Issue by mathiasene** [TomasMikula/RichTextFX#138]
Does RichTextFX supports multiple selection, or a possibility to add the support?

**Comment by TomasMikula** [comment]
Hi, do you mean selecting multiple disconnected ranges of text? It is not supported. Selection is modeled as a single range of text `[start, end)`.

You can of course fork RichTextFX and extend it with multiple selection functionality. You would have to extend the model to support multiple ranges, as well as the _skin_ that handles the graphical rendering.

**Comment by mathiasene** [comment]
Can you name the specific classes, so can I try to extend it. And come with some more functionalities to RichTextFX? :smile:

**Comment by TomasMikula** [comment]
Selection is tracked in the [StyledTextArea](https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java) class. Look for `selection` and `internalSelection` properties there. As you can see there, selection is a single `IndexRange`. You may want to change it to `ObservableList<IndexRange>`.

`selection` is then used in [StyledTextAreaVisual](https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/skin/StyledTextAreaVisual.java).

**Comment by JordanMartinez** [comment]
This issue was duplicated in #222 except that issue also includes multiple carets.

Not sure if you're still trying to implement this feature @mathiasene, but it might also help to check out #222 as I've left some thoughts that will help the person that implements it.

**Comment by JordanMartinez** [comment]
Closing as #222 is more recent and has more information on this issue.
