### ISSUE TITLE
No [ ] { } writable on OS X 10.10.3 in CodeArea

### ISSUE THREAD

**Issue by Morvs** [TomasMikula/RichTextFX#139]
Hi,

I was trying to write a code editor with your lib but I can't write brackets or curly braces. I'm using a german layout on a Macbook where brackets are written with ALT + 5/6 and curly braces with ALT + 8/9. To be exact none of the symbols requiring ALT are writable.
I'm not that sure right now but I thought it was working with 10.10.2 as I was testing it some days ago before the third update of 10.10.
I tried both the demos of Java syntax highlighting and using eclipse with this code but I can't write them. Copy pasting them works though.

Also, using Windows 8.1 on the same Macbook running the same demos I am able to write those brackets and curly braces so it seems to be system specific.

If you've got any idea of what's the issue or if I can provide any further information, just let me know.

**Comment by TomasMikula** [comment]
Thanks for reporting. Can you try whether they work in a plain JavaFX TextArea?

**Comment by Morvs** [comment]
Just tried it with the code from here -> http://www.java2s.com/Code/Java/JavaFX/UsingTextAreatodisplaymorelines.htm

It works flawlessly with the usual TextArea.

**Comment by Morvs** [comment]
Just a little note: I was on a little bit outdated jdk (8_u25) which i noticed this morning but updating to the current version 8_u40 didn't help either. I also noticed that my project in eclipse was set to use jdk 1.5 but as you may expect, changing to 1.8 sadly didn't help.

**Comment by TomasMikula** [comment]
Please, try this with the new 0.6.4 release.

**Comment by Morvs** [comment]
Now it's working (again).

Thank you for solving the issue.
