### ISSUE TITLE
Question: Set the initial text of the rich text area

### ISSUE THREAD

**Issue by benedictleejh** [TomasMikula/RichTextFX#140]
I've been looking through all the documentation but I can't quite find a way to correctly set the initial text of the rich text area. Using `replaceText` or `insertText` causes the action to be registered into the undo manager, which means that triggering an undo action will remove what is supposed to be the initial value of the text box. Is there a way to do this?

**Comment by TomasMikula** [comment]
Hi Benedict. Currently, the only way to get have some initial text is to insert it. However, you can tell the undo manager to forget history, so that it does not undo this initial insert:

    area.getUndoManager().forgetHistory();
