### ISSUE TITLE
How do I update display of text that uses an old version of style object with its updated version?

### ISSUE THREAD

**Issue by JordanMartinez** [TomasMikula/RichTextFX#142]
Please tag this as a question...

If text is inserted into StyledTextArea or InlineStyleTextArea with a custom style object named 'customStyle' (let's say the style makes the text's color red), and later I want to update customStyle (so that now the style makes the text's color green), how would I update all the text that uses the old version of the style to be displayed as the new version of the style?

Would I need to find every case that uses the old style and set that text with the new version of the style? Or do the areas have a way of doing this automatically?

**Comment by TomasMikula** [comment]
Hi Jordan,

there is a semi-automatic way:

```java
StyleSpans<CustomStyle> styleSpans = area.getStyleSpans(0, area.getLength());
StyleSpans<CustomStyle> newSpans = styleSpans.mapStyles(style -> {
    return style.equals(oldStyle) ? newStyle : style;
});
area.setStyleSpans(0, newSpans);
```

**Comment by JordanMartinez** [comment]
Thanks for clarifying that.

However, I'm using Groovy instead of Java, so the code above (and my efforts at translating it into a syntax that Groovy understands) isn't working. Since the problem might be due to using Groovy (and thus something else I do before I run this code) rather than Java, I'll post a new issue.
