### ISSUE TITLE
Dynamic keyword highlighting

### ISSUE THREAD

**Issue by moisson** [TomasMikula/RichTextFX#147]
Hello Thomas,

I don't have much experience with Java and I wonder if it would be possible to use your CodeArea to highlight keywords based on a dynamic list of keywords ?

If yes, what should I work on ?

Thanks in advance

**Comment by mathiasene** [comment]
You can update the highlighting pretty easy, if that's what you mean? You just need to write the same highlighting code again, and so will it update the highlighting. So can you change keywords like "if", "else" to "try", "catch". It'll update automatic. Just use this code:

textProperty().addListener((obs, oldText, newText) -> {
	setStyleSpans(0, computeHighlighting(newText));
});

So will it highlight it when this code run. It'll do it in a second, or close to.

**Comment by TomasMikula** [comment]
If you are new to Java and JavaFX, a good place to start is to make sure you understand how the [JavaKeywords demo](https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywords.java) works.

In there, you will see that keywords are stored in a fixed array of strings:

```java
private static final String[] KEYWORDS = new String[] {
    // ...
};
```

You will want to change that to be an `ObservableList` of strings:

```java
private static final ObservableList<String> KEYWORDS = FXCollections.observableArrayList(
    // ...
);
```

Then turn anything that depends on `KEYWORDS` into observable:

```java
private static final ObservableValue<String> KEYWORD_PATTERN = ...;

private static final ObservableValue<Pattern> PATTERN = ...;
```

Finally, add a listener to `PATTERN` and trigger highlighting when it changes.
