### ISSUE TITLE
creating multiple layers of StyleSpans for the StyledTextArea

### ISSUE THREAD

**Issue by pnixon** [TomasMikula/RichTextFX#151]
I would like to create a regex text highlighter using your RichTextFX that will highlight the same document on multiple separate lines with multiple regular expressions. I am running into an issue where when I run StyleSpansBuilder.create() I cannot then put another layer on top. I have also tried creating multiple stylespansbuilders but only one will show at a time.

The problem with running multiple regular expressions with a single stylespansbuilder is that each match after the first is assumed to be after the previous match, I assume this is probably to ensure that overlap doesn't happen accidentally, but this is actually behavior that I want. 

My setup right now is basically  a single window with two codeAreas, the top holds multiple lines of regex, the bottom holds the document that the regular expressions are to be run on and highlighted. could you point me in the right direction? I've been trying to make sense of your framework here, but there's enough to keep me busy for weeks trying to figure out exactly how they work.

Thanks, and this RichTextFX is pretty damn cool.

**Comment by TomasMikula** [comment]
> I am running into an issue where when I run StyleSpansBuilder.create() I cannot then put another layer on top. I have also tried creating multiple stylespansbuilders but only one will show at a time.

Yes, when you call `setStyleSpans`, the previous styles are overridden. Thus when you call `setStyleSpans` multiple times, only the last call will take effect.

> The problem with running multiple regular expressions with a single stylespansbuilder is that each match after the first is assumed to be after the previous match, I assume this is probably to ensure that overlap doesn't happen accidentally, but this is actually behavior that I want.

This is how [Matcher.find()](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Matcher.html#find--) works by default and that behavior is desirable in the Java highlighting demo. However, it is _just_ a demo. RichTextFX does not care _how_ you construct the `StyleSpans`.

From your description, the easies solution seems to me to write a function that merges two `StyleSpans` into one:

    static StyleSpans<S> merge(StyleSpans<S> s1, StyleSpans<S> s2, BinaryOperator<S> mergeStyles) {
        // implement this
    }

`StyleSpans<S>` is conceptually just a list of `StyleSpan<S>`s, where `StyleSpan<S>` is conceptually just a pair `(int length, S style)`.

Let's `/` and `\` denote two instances of style (of type `S`) and let `X = mergeStyles(/, \)` (i.e. `X` is the combination of `/` and `\`).  Then `merge` should behave like this:

                            s1 = |    ////////    ////        //////  |
                            s2 = |\\\\\\    \\\\        \\\\          |
    merge(s1, s2, mergeStyles) = |\\\\XX////XX\\  ////  \\\\  //////  |

Using `merge`, you can then "overlay" any number of `StyleSpans` and use the result in `setStyleSpans`.

I hope this was helpful.

Also, such a `merge` function would be a useful addition to `StyleSpans`, so a pull request would be welcome ;)

**Comment by pnixon** [comment]
Sounds good, I'll get on that. If i run into problems, you won't mind me bothering you about them on here would you?

**Comment by TomasMikula** [comment]
Sure, no problem.

**Comment by MewesK** [comment]
Hi Tomas,

sadly it wasn't feasible for my purpose to use your internal StyleSpans to perform the merge operation for multilayer styles. I'm using a simple Span class with a start and an end in addition to a builder class to merge everything and translate it to your StyleSpans.

This way way much cleaner since I don't have to recalculate the start end based on the length/position provided by your internal format. But of course it isn't a general purpose approach like some may want. However it works fine for multiple highlighting layers.

 Heres the GIST: https://gist.github.com/MewesK/e70a95126d6cd90fdc48

Greetings,
Mewes

**Comment by TomasMikula** [comment]
Version 0.6.9 has [StyleSpans#overlay](http://www.fxmisc.org/richtext/javadoc/org/fxmisc/richtext/StyleSpans.html#overlay-org.fxmisc.richtext.StyleSpans-java.util.function.BiFunction-) method.
