### ISSUE TITLE
Weird cursor position behavior

### ISSUE THREAD

**Issue by jmak35** [TomasMikula/RichTextFX#154]
Hi Tomas,

Would like to say first of all how awesome your project is, good work.

In saying that, we've recently upgraded from version 0.5.1 to 0.6.4. Everything seems to be working fine, except for when we're navigating the position of the cursor/caret. I'll try to describe the scenario as best I can but it's probably easier to see it in action. In fact, if you run the JavaKeywords.java demo, you'll be able to reproduce it.

The issue is, when you run the demo, if you place the cursor on say the last line to right of the closing curly bracket, and then use the up arrow key to navigate up, it actually moves the cursor to the start of the line. If you then press up again, the cursor doesn't move. Usually in this scenario, pressing the up arrow should move the cursor up to the next line, which is the behavior you would expect.

If you repeat the process, and instead of pressing the up arrow, press the left arrow and it navigates to the left of the curly bracket. If you then press up, it is able to move into the blank line.

Another scenario is if you use the mouse to click on blank lines, it actually doesn't allow the cursor to move into the blank line, unless you click to the left of the carriage return of that blank line, i.e. essentially on the gutter.

The behavior and expectation of cursor position as a result of arrow keys and mouse clicks would be the same at the behavior of the editor into which I'm writing right now. I hope this can be fixed as soon as possible as it is critical to our application. Thank you in advance.

Cheers.

**Comment by TomasMikula** [comment]
Hi, I cannot reproduce any of the described behaviors. Everything seems to work fine on my end. Note that the recommended Java version is 8u40.

**Comment by jmak35** [comment]
Thanks for the response Tomas. Hmm ok, we're using 8u25. I'll update and see whether it fixes things. In the meantime, is it possible if you could please try it with 8u25, just so I can be sure I'm not imagining things!

**Comment by TomasMikula** [comment]
I can reproduce the issue with 8u31.

**Comment by jmak35** [comment]
Ok thanks for confirming that Tomas. I'm just in the middle of upgrading my java environment at the moment. Once I can confirm that it works fine, I'll close this issue. Appreciate the quick response, thank you :-)

**Comment by jmak35** [comment]
Confirmed that the issue disappears on Java 8u45. Thanks again!
