### ISSUE TITLE
Select--drag text moves characters, but not their style

### ISSUE THREAD

**Issue by melkhaldi** [TomasMikula/RichTextFX#169]
Here is the behavior in word-pad on windows vs the richtext demo.. This is also true for the character style.
![moving text with background](https://cloud.githubusercontent.com/assets/5727365/9424988/4a5dd39a-48b5-11e5-93cb-ba3ab5cc1d55.gif)

**Comment by TomasMikula** [comment]
Yeah... This is not specific to background. Any kind of style gets lost with dragging. Thanks for reporting.

**Comment by TomasMikula** [comment]
It is now fixed if you build from source.
