### ISSUE TITLE
Possibly Memory Leak

### ISSUE THREAD

**Issue by mfaustin** [TomasMikula/RichTextFX#176]
Hi Tomas, I was trying the Markdown Writer FX and noticed a strange memory usage when I'm scrolling a text up/down. Later I reproduced it in RichTextFX demo. When I pasted a text the used heap was 11M after scrolling up/down during few minutes the used heap became 753M. 

![screenshot from 2015-09-05 15-50-39](https://cloud.githubusercontent.com/assets/9551365/9699358/ec2b3468-53e8-11e5-970b-ac8757df97b0.png)

I'm using Oracle Java 8u60. The same thing happened using Oracle Java 9 Build b78.

![screenshot from 2015-09-05 15-54-46](https://cloud.githubusercontent.com/assets/9551365/9699424/069b031c-53eb-11e5-9033-80ea6e23d9d1.png)

**Comment by JordanMartinez** [comment]
Is this similar to #159 in any way? A problem with Weak Listeners ?

**Comment by mfaustin** [comment]
I don't know exactly. I looked at https://bugs.openjdk.java.net/browse/JDK-8130458 it was fixed but the build b78 still leaks

**Comment by TomasMikula** [comment]
Hi, thanks for reporting. It seems like the same issue. Although https://bugs.openjdk.java.net/browse/JDK-8130458 was fixed recently, I doubt it made it into JDK 9 b78.

**Comment by TomasMikula** [comment]
I have written a workaround for it. Try it out with version 0.6.7.

**Comment by mfaustin** [comment]
Yes problem solved. Thanks!
