### ISSUE TITLE
IOOB Exception when hitting backspace

### ISSUE THREAD

**Issue by asetty** [TomasMikula/RichTextFX#179]
To reproduce the error just press the enter key and then backspace.

        import org.fxmisc.richtext.StyleClassedTextArea;
        import javafx.application.Application;
        import javafx.scene.Scene;
        import javafx.scene.layout.BorderPane;
        import javafx.stage.Stage;
        public class App extends Application {

	@Override
	public void start(Stage primaryStage) throws Exception {
		 
	    StyleClassedTextArea ta = new StyleClassedTextArea();
	    ta.setPrefSize(600,600);
	    ta.setWrapText(true);
	    ta.setLayoutX(0);
	    ta.setLayoutY(0);
     
	    BorderPane root = new BorderPane(ta);
            primaryStage.setScene(new Scene(root, 600, 600));
            primaryStage.show();

	}

	public static void main(String[] args) {
        launch(args);
    }
      }

**Comment by TomasMikula** [comment]
Thanks for reporting. It is also reproducible in the demos whenever there is a newline at the end of text. This was likely introduced in my recent refactoring of newline handling. It is now fixed in the source code and I will publish a new release soon.

**Comment by TomasMikula** [comment]
See [release 0.6.9](https://github.com/TomasMikula/RichTextFX/releases/tag/v0.6.9).
