### ISSUE TITLE
Use as a WYSIWYG Editor with html text in background and styled design in front

### ISSUE THREAD

**Issue by IntelligyScience** [TomasMikula/RichTextFX#181]
Hi,

this is a great project. And I try to familiar with your project. But at this moment I have a few problems with that.
I have to build an editor WYSIWYG like the HTMLEditor in JavaFX. My problem is at this moment, in background I generate a html text. Of course without head and body. Only the text for a paragraph and the inline code for maybe bold or italic. Like `<b>` oder `<i>`.

Now maybe the user wants to add a colored text at a special caret position. Do I have the caret position inside the html text? And how I can realize that I have the possibility to add `<b>` in htmltext and show only the bolder in WYSIWYG? I try to implemented InlineCssTextArea and I can transform a few things like `<b>` or `<i>`.

Do you have a special version of this editor?

Thank you

**Comment by melkhaldi** [comment]
if I understand your question correctly, here is the info you need:

richtext data structure is made of paragraphs, that are made if styledtext,
which are text+styles.

There are methods to get paragraphs from a text area, its text and its
style segments, and each segment has a length. So you can compute segments
start positions starting from 0 then adding segments lengths.

So what the user hits save, you parse the text area info and write to/open
a text file where you open a <p> for each parapgraph, append style and text
for each segment, then close your parahraph. do this for each paragraph and
you get your html code as an ASCII text file. You close the text file and
set its extenion to html.

I hope this helps.

Hi,

this is a great project. And I try to familiar with your project. But at
this moment I have a few problems with that.
I have to build an editor WYSIWYG like the HTMLEditor in JavaFX. My problem
is at this moment, in background I generate a html text. Of course without
head and body. Only the text for a paragraph and the inline code for maybe
bold or italic. Like * oder .*

Now maybe the user wants to add a colored text at a special caret position.
Do I have the caret position inside the html text? And how I can realize
that I have the possibility to add * in htmltext and show only the bolder
in WYSIWYG? I try to implemented InlineCssTextArea and I can transform a
few things like or .*

Do you have a special version of this editor?

Thank you

—
Reply to this email directly or view it on GitHub
<https://github.com/TomasMikula/RichTextFX/issues/181>.

**Comment by IntelligyScience** [comment]
Hi
this is not exactly what I mean.

I have a fully styled html paragraph. This can contains for example things like <ul>.

Now I hoped that this editor has the possibility to set a htmlText in background. The visual editor shows the styled html. And each caret, for example carte position 5 would be caret position 8 in html text.

Ok, so I have to build this by my self.
Thanks for your help

**Comment by melkhaldi** [comment]
from what I know, RichTextFX is made intentionally abstract with only the
needed low level functions so that it is used as base for other things.
special behaviors are typically added on top.

I would wait to hear from Tomas, there might be a way to do this. I was
trying to give feedback from my experience working with the library in case
you needed quick help :)

**Comment by TomasMikula** [comment]
Hi André,

RichTextFX is not going to magically know the index within HTML.

I eventually want to support custom implementations of what is now called `EditableStyledDocument`. Your implementation of `EditableStyledDocument` could then hold HTML text (or some kind of syntax tree or DOM) and provide a _view_ of it as a sequence of paragraphs for RichTextFX to render. Even then, however, resolving text indexes to html indexes would be the job of your custom `EditableStyledDocument` implementation.

Also note that you can reasonably map only a subset of HTML to styled text. Things like tables will not work.

**Comment by IntelligyScience** [comment]
Hi Thomas,

thats sound great. Yes I know thinks like table are not relevant to me. 
But you eventually plan to support. So this is not implemented, do it not?

At this moment implemented by my self the normal styling things like <b>, <font ...> <i> and so on.

André

**Comment by TomasMikula** [comment]
Yes, that is unfortunately not supported right now, but I plan to add it in the future.

**Comment by JordanMartinez** [comment]
I'm closing this since Tomas' suggestion of a custom ESD can be done now, even if tables are not yet supported at this time.

**Comment by elkebasel** [comment]
I am working with JavaFX in connection with jpro webserver, which means that neither HTMLEditor nor SwingNodes are supported.
I would like to parse the document output as html as described in this thread.
My question:
I have a bullet list with two layers.
![Bildschirmfoto vom 2020-12-01 20-03-11](https://user-images.githubusercontent.com/47090890/100787043-5204c780-3413-11eb-857a-6d5b2c12126b.png)
the output of the paragraphs is:
Par[; StyledSegment(segment=left(text 1) style=12,Serif,0x000000ff)]
Par[; StyledSegment(segment=left(text 2) style=12,Serif,0x000000ff)]
Par[; StyledSegment(segment=left(text 3) style=12,Serif,0x000000ff)]
Par[; StyledSegment(segment=left(text 4) style=12,Serif,0x000000ff)]
where do I find the information about the bullets and the indents? 
Thank you very much in advance for your answer!
Best, Elke

**Comment by Jugen** [comment]
I think that for each paragraph you would need to extract it's paragraph style using: `getParagraphStyle()`
So for example: `area.getParagraph(0).getParagraphStyle()`

**Comment by elkebasel** [comment]
Dear Jurgen
Thank you for your fast reply!
This is my Code:

for(int i =0; i< doc.getParagraphs().size(); i++){
System.out.println("paragraph "+doc.getParagraph(i));
System.out.println("style "+doc.getParagraph(i).getParagraphStyle());
}

and this is what I get:
paragraph Par[; StyledSegment(segment=left(text 1) style=12,Serif,0x000000ff)]
style
paragraph Par[; StyledSegment(segment=left(text 2) style=12,Serif,0x000000ff)]
style
paragraph Par[; StyledSegment(segment=left(text 3) style=12,Serif,0x000000ff)]
style
paragraph Par[; StyledSegment(segment=left(text 4) style=12,Serif,0x000000ff)]
style

So the style seems not to be set.
This is in Java 11/JavaFX15 which the pro server wants; I had to give manually the stylesheet, no CSS errors or warnings.

this.getStylesheets().add("/org/fxmisc/richtext/demo/richtext/rich-text.css");
(this is a VBox in which I wrapped the Editor)

For the sample, I use Java 1.8 build 212. Here I get a warning:
/usr/lib/jvm/jdk1.8.0_212/bin/java -
WARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.label' in stylesheet jar:file:/usr/lib/jvm/jdk1.8.0_212/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dez 01, 2020 9:20:17 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.label' in stylesheet jar:file:/usr/lib/jvm/jdk1.8.0_212/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
pargraphPar[; StyledSegment(segment=left(text 1) style=12,Serif,0x000000ff)]
style
pargraphPar[; StyledSegment(segment=left(text 2) style=12,Serif,0x000000ff)]
style
pargraphPar[; StyledSegment(segment=left(text 3) style=12,Serif,0x000000ff)]
style
pargraphPar[; StyledSegment(segment=left(text 4) style=12,Serif,0x000000ff)]
style

Do you have any idea what is going wrong?
Best, Elke

**Comment by Jugen** [comment]
Ah sorry, my bad - my suggestion applies to the next release, which I think will be next week sometime.
In the mean time you can look at the latest [ParStyle](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/ParStyle.java) and update your code with it if you want.

_ParStyle_ has the following new methods that apply to your use case:
```java
    public boolean isIndented() {
        return indent.map( in -> in.level > 0 ).orElse( false );
    }

    public Indent getIndent() {
        return indent.get();
    }
```

**Comment by Jugen** [comment]
@elkebasel also see PR 987 to help you with this.
Feel free to comment there as well.

**Comment by elkebasel** [comment]
Thank you once more, dear Jurgen, this me for shooting an invisible trouble.

I will have a look.

 

Best, Elke

 

Von: Jurgen <notifications@github.com> 
Gesendet: Mittwoch, 2. Dezember 2020 07:59
An: FXMisc/RichTextFX <RichTextFX@noreply.github.com>
Cc: elkebasel <info@elkehofmann.net>; Comment <comment@noreply.github.com>
Betreff: Re: [FXMisc/RichTextFX] Use as a WYSIWYG Editor with html text in background and styled design in front (#181)

 

Ah sorry, my bad - my suggestion applies to the next release, which I think will be next week sometime.
In the mean time you can look at the latest ParStyle <https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/ParStyle.java>  and update your code with it if you want.

ParStyle has the following new methods that apply to your use case:

    public boolean isIndented() {
        return indent.map( in -> in.level > 0 ).orElse( false );
    }
 
    public Indent getIndent() {
        return indent.get();
    }

**Comment by elkebasel** [comment]
Dear Jugen
I tried your advice, and I can read the indents of the bullet list.
Am I right that "Indent" does always mean bulleted list (as when I put a normal tabulator it is treated as part of the text)?
I will try to implement myself a numbered list, this will help to learn how richtextfx works.
Thank you very much so far, you helped me a lot.
Best, Elke

**Comment by Jugen** [comment]
Dear Elke, well done.
Yes, an "Indent" always indicates a bulleted list and never a tab.
Have fun, best
Jürgen
