### ISSUE TITLE
Lines without characters

### ISSUE THREAD

**Issue by kanashius** [TomasMikula/RichTextFX#188]
Just try to write in a Line, where nothing stands. The cursor just jump over it (keyup,...). Sometimes it jumps down, sometimes not. littlebit crazy :)

**Comment by TomasMikula** [comment]
I cannot reproduce this. It probably has to do with recent Windows newlines problems. Are you on Windows? If you can, please try the [snapshot release](https://github.com/TomasMikula/RichTextFX#snapshot-releases).

**Comment by kanashius** [comment]
Yes, I´m working at Windows. What is this snapshot release? Another Jar, or just an option?

**Comment by TomasMikula** [comment]
It is a jar that has not been released yet. It is built from the most up to date source code. It is really easy to use if you use a dependency manager like gradle or maven.

**Comment by TomasMikula** [comment]
Closing as the issue could not be reproduced.
