### ISSUE TITLE
CodeArea.getStyleSpans(from, to).append(...) does not append

### ISSUE THREAD

**Issue by jmak35** [TomasMikula/RichTextFX#191]
Hi Tomas,

I'm getting an issue with using the above method like so:

```
StyleSpans<Collection<String>> styleSpans = codeArea.getStyleSpans(startIndex, startIndex + text.length());

StyleSpansBuilder<Collection<String>> spansBuilder = new StyleSpansBuilder<>();
spansBuilder.add(Collections.singleton("class1"), text.length());
spansBuilder.add(Collections.singleton("class2"), text.length());

spansBuilder.create().forEach(styleSpans::append);
```

After this code executes, styleSpans still has a length of 0. If it was unmodifiable I'd assume it would've thrown an exception, but I believe that is not the case.

Is there anything I'm doing wrong?

Thank you.

**Comment by TomasMikula** [comment]
Hi, `StyleSpans` is indeed unmodifiable. `append` returns a new instance. The original one remains intact.

Anyway, if `styleSpans` has length 0, that would mean that `text.length()` is 0.

**Comment by TomasMikula** [comment]
Closing this as this is not an issue.
