### ISSUE TITLE
RichText-Demo is not working

### ISSUE THREAD

**Issue by reitffunk** [TomasMikula/RichTextFX#194]
Hi,

I cannot start the RichText-Demo.

java -cp richtextfx-demos-fat-0.6.10.jar org.fxmisc.richtext.demo.richtext.RichText cannot find the mainclass and when I try to run it in Netbeans it says, that this part should only have one parameter:

private final InlineStyleTextArea<TextStyle, ParStyle> area...

Nevertheless I was able to get it to work with the InlineStyleTextArea, because of the code on the Startpage:

InlineStyleTextArea<MyStyleInfo> area =
        new InlineStyleTextArea<>(new MyStyleInfo(), styleInfo -> styleInfo.toCss());

Best regards, Malte

**Comment by TomasMikula** [comment]
Hi,

I see. In the latest sources I moved the RichText demo to its own package and updated the README, but that change is not yet in the release, so I should probably have waited with updating README. You should be able to run it with the old class name:

    java -cp richtextfx-demos-fat-0.6.10.jar org.fxmisc.richtext.demo.RichText

**Comment by TomasMikula** [comment]
The command now matches the class name in the new 0.7-M1 pre-release.
