### ISSUE TITLE
CodeArea in Dialog wrong caret position calculation

### ISSUE THREAD

**Issue by daa84** [TomasMikula/RichTextFX#196]
Embed CodeArea to javafx javafx.scene.control.Dialog:
```java
CodeArea codeArea = new CodeArea();
dialog.getDialogPane().setContent(codeArea);
```
Then try to select portion of text - looks like cursor position a bit shifted from original one, so it is hard to point to exact symbol.

**Comment by TomasMikula** [comment]
Hi, thanks for reporting. Can you provide a self-contained (a single `.java` file) example that reproduces the issue?

Thanks,
Tomas

**Comment by daa84** [comment]
```java
import javafx.application.Application;
import javafx.scene.control.*;
import javafx.stage.Stage;
import org.fxmisc.richtext.CodeArea;

public class Test extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        Dialog<Boolean> dialog = new Dialog<>();

        CodeArea codeArea = new CodeArea("Text\nText\nText");
        dialog.getDialogPane().setContent(codeArea);
        dialog.getDialogPane().getButtonTypes().add(ButtonType.OK);

        dialog.showAndWait();
    }
}
```
Try to position cursor by mouse to first line. Align mouse cursor to center of first line and click - cursor places on second line. In non dialog mode it works ok.

**Comment by TomasMikula** [comment]
Thank you, I can reproduce the problem. So it seems that dialog adds some padding to its content node and `CodeArea` does not compensate for it.

A workaround is to wrap `codeArea` in an extra node, such as a `StackPane`:

```java
dialog.getDialogPane().setContent(new StackPane(codeArea));
```

**Comment by daa84** [comment]
Thank you for workaround.

**Comment by ondrej-kvasnovsky** [comment]
Or if you really have to hack it, then you might go to StyledTextAreaView and subtract the margin (5 pixes in the following example) there... not nice solution, but a working one.
```java
    CharacterHit hit(double x, double y) {
        double xMinusMargin = x - 5;
        double yMinusMargin = y - 5;
        VirtualFlowHit<Cell<Paragraph<S, PS>, ParagraphBox<S, PS>>> hit = virtualFlow.hit(xMinusMargin, yMinusMargin);
```

**Comment by JordanMartinez** [comment]
Using Linux and this version of Java
````
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
````
I couldn't reproduce this problem with the above example.
Can another check and confirm whether this case arises on a different OS?

**Comment by TomasMikula** [comment]
Now I can't reproduce it either, tried also with JDK 1.8.0_40. Not sure what version I tested this before, but dialogs were only added in 1.8.0_40 I believe... Weird.

**Comment by daa84** [comment]
Problem still exists on windows platform, tested with jdk 1.8.0_65

**Comment by daa84** [comment]
ups, sorry, i use old richtextfx version, latest version from git work fine for me.

**Comment by daa84** [comment]
in latest git version this issue fixed.
