### ISSUE TITLE
CodeArea's caret blink rate is too quick

### ISSUE THREAD

**Issue by hwaite** [TomasMikula/RichTextFX#203]
CodeArea's default caret blink rate should match standard JavaFX text controls. Probably needs to be slowed down by about 25%.

    public class Test extends Application {
        public static void main(String[] args) {launch(args);}

        public void start(Stage pStage) {
            pStage.setTitle("Test");

            final Pane root = new VBox();

            root.getChildren().addAll(
                new CodeArea(), new TextArea(), new TextField()
            );

            pStage.setScene(new Scene(root, 300, 250));
            pStage.show();
        }
    }

**Comment by TomasMikula** [comment]
Can you find out what the TextArea's frequency is? RichTextFX's is 500ms.

**Comment by hwaite** [comment]
`System.out.println((new JTextArea()).getCaret().getBlinkRate())` returns 0.5. Also, TextInputControlSkin.CaretBlinking includes below snippet:

    caretTimeline.getKeyFrames().addAll(
        new KeyFrame(Duration.ZERO,
                event -> {
                    setBlink(false);
                }
        ),
        new KeyFrame(Duration.seconds(.5),
                event -> {
                    setBlink(true);
                }
        ),
        new KeyFrame(Duration.seconds(1)));


Looks like I'm mistaken: 0.5 *is* the correct rate. Sorry about that; I'll close this bug.
