### ISSUE TITLE
CodeArea Jump to a Specific Line

### ISSUE THREAD

**Issue by mellwa** [TomasMikula/RichTextFX#208]
Hi Tomas,

Thank you for the quick reply in email. I tried moveTo(int) before but it didn't work. The file still shows the first line. 
    CodeArea codeArea = new CodeArea();
    codeArea.setParagraphGraphicFactory(LineNumberFactory.get(codeArea));
    codeArea.appendText(content);
    codeArea.setWrapText(true);
    codeArea.moveTo(1000);

    Scene scene1 = new Scene(codeArea, 800, 600);
    Stage stage = new Stage();
    stage.setTitle(objects[0].toString());
    stage.setScene(scene1);
    stage.show();
Also, the moveTo() method seems like only accept int value but codeArea.position(x, 0) gives a Position type value. Is there any other way to jump to a specific line?

**Comment by TomasMikula** [comment]
You are right, it should be

    codeArea.position(x, 0).toOffset()

`moveTo()` doesn't work on startup again because skin hasn't been initialized. Try to put it inside a `Platform.runLater()` and after `stage.show()`:

```java
stage.show();
Platform.runLater(() -> codeArea.moveTo(codeArea.position(1000, 0).toOffset()));
```

**Comment by mellwa** [comment]
It works! Thank you, Tomas!
