### ISSUE TITLE
Subclass denied acces to CharacterHit

### ISSUE THREAD

**Issue by JordanMartinez** [TomasMikula/RichTextFX#218]
Relating to #217, `CharacterHit` isn't accessible to subclasses of `StyledTextArea`, making it impossible to use when customizing `MouseEvent` handling. Besides this use case, there might be (though I can't think of any right now) other skin-related classes/methods that should now be `protected` instead of `package-private` since the Skin has been in-lined.

**Comment by TomasMikula** [comment]
We can now open more of this functionality. It should be use-case driven, though.

**Comment by JordanMartinez** [comment]
Aye... I guess I'll rename this issue to only focus on CharacterHit. We can open new issues for other use-cases when they arise.

**Comment by JordanMartinez** [comment]
Resolved via 9032e6361be538ca9760c79e8dbd9b4ae2e820fb
