### ISSUE TITLE
Support background color for a range of text

### ISSUE THREAD

**Issue by melkhaldi** [TomasMikula/RichTextFX#22]
Hi Tomas, 
I am in the process of implementing a highlighting method. 
I am doing this simple code. I verified all values, they are all fine.

tempStype = "-fx-background-color: yellow;" ;
indexRange =richText.getSelection();
richText.setStyle(indexRange.getStart(), indexRange.getEnd(), tempStyle);

I notice a change in the range style, but the background is not affected. Is it broken? Can you verify?

**Comment by TomasMikula** [comment]
This is now resolved by #166 thanks to @MewesK. The name of the property is `-fx-background-fill`.
