### ISSUE TITLE
Only blink caret when not moving

### ISSUE THREAD

**Issue by wyozi** [TomasMikula/RichTextFX#227]
If you hold down an arrow key the caret still keeps blinking, which makes navigation significantly harder. Would it be possible to pause the blinking while navigating using arrow keys?

**Comment by wyozi** [comment]
Also related to this: seems like the caret is in the "invisible" phase of blinking when focusing the code area. This makes the user interaction with the area seem a bit clumsy.

**Comment by JordanMartinez** [comment]
I believe this is a duplicate of #189. Both of the issues you raise were fixed in `master` (see dd5eda73d829b169cc4127423f944488d9127b98) but Tomas hasn't made a release yet that includes the bug fix.

**Comment by wyozi** [comment]
Ahh, I briefly read the source code but completely missed the `caretDirty`. Nice!
