### ISSUE TITLE
Include text background color in demos

### ISSUE THREAD

**Issue by Zomis** [TomasMikula/RichTextFX#230]
It is currently not obvious that #22 is possible, it took some googling to find out that it was available.

I suggest showcasing this feature in one of the demos, such as the JavaKeywordsDemo, to make it more obvious that it is possible - and to show *how* it is possible.

(Many thanks for the fact that it actually is possible btw)

**Comment by TomasMikula** [comment]
Hi Simon, the RichText demo allows you to change the background of a range of text, as well as of the whole paragraph. The toolbar of the demo is not great though, one would have to just try the color pickers to see what they do. If you want to improve the demo, I would welcome a pull request.

**Comment by TomasMikula** [comment]
Closing this since setting the background color is already part of the RichText demo.
