### ISSUE TITLE
VirtualizedScrollPane Doesn't appear in the jar

### ISSUE THREAD

**Issue by surnaturelDev** [TomasMikula/RichTextFX#236]
When I want to recompile the sources of JavaKeywordsAsync I got this error : (unfounded class)

![virtualizedscrollpane](https://cloud.githubusercontent.com/assets/16513804/12074867/fafc6f2e-b163-11e5-8d31-257fd0eac956.png)

**Comment by JordanMartinez** [comment]
Are you using the latest stable release (which should include that yet)? Or did you compile from source (which I just did and it worked fine)?

**Comment by surnaturelDev** [comment]
just from the source 
but i'am using the latest stable release
can you give me your javakeyword.java

**Comment by JordanMartinez** [comment]
Ok, so you cloned the repository, checked out the latest stable release (0.6.10), and then built it from source using Gradle, correct? And for some reason, the error you come across is that `VirtualizedScrollPane` is not within the outputted jar, right?

**Comment by surnaturelDev** [comment]
i found a solution but isn't 100% correct 
i decompile the JavaKeywords.class (i get from the jar file before zipping) and i use this website : http://www.javadecompilers.com/ 
In the latest they change the virtualizedScrollpane :

//Scene scene = new Scene(new StackPane(new VirtualizedScrollPane<>(codeArea)), 600, 400);
 Scene scene = new Scene((Parent) new StackPane(new Node[]{codeArea}), 600.0, 400.0);

and it work :)

**Comment by JordanMartinez** [comment]
I'm not sure I'm following you.

**Comment by iaz33m** [comment]
I am Facing same problem here , can anyone help me out with this.

![screenshot_11](https://cloud.githubusercontent.com/assets/17041893/12776660/ba64e6d8-ca79-11e5-9708-90b3db6450e2.png)

i include latest stable version , here is my pom file

![screenshot_12](https://cloud.githubusercontent.com/assets/17041893/12776698/fdfaad1a-ca79-11e5-8e01-95780a91432e.png)

**Comment by JordanMartinez** [comment]
My guess is that it's a conflict of dependencies....
Flowless 0.4.7 doesn't yet include VirtualizedScrollPane. That was implemented in later commits. Have you tried updating Flowless to its SNAPSHOT version?

**Comment by JordanMartinez** [comment]
Snapshot version is "0.5-SNAPSHOT"

**Comment by iaz33m** [comment]
i try it now but it ways : Missing artifact org.fxmisc.flowless:flowless:jar:0.5-SNAPSHOT

**Comment by JordanMartinez** [comment]
The snapshot version is stored via the [OSS Sonatype server](https://oss.sonatype.org/content/repositories/snapshots/org/fxmisc/flowless/flowless/0.5-SNAPSHOT/), not Maven Central. Could that be why the artifact is missing?

**Comment by EMostafaAli** [comment]
I have the exactly same problem, will flowless be updated through maven soon?

**Comment by kuc** [comment]
>Could that be why the artifact is missing?

I'm using OSS Sonatype server and never had any problems with using SNAPSHOT version, so maybe yes.

**Comment by JordanMartinez** [comment]
@kuc That's pretty much what I concluded, too... 

Looking at @surnaturelDev's reply to my initial comment, I now understand that he compiled RichTextFX from source but is using the latest stable `Flowless` release (0.4.7) and not the SNAPSHOT release.

**Comment by FrancescoTaurino** [comment]
@JordanMartinez  hi, I am facing same problems. I downloaded "flowless-0.5-20160410.174114-12.jar" from OSS Sonatype server and "richtextfx-fat-0.6.10.jar". 
I am trying to run your demo codes but VirtualizedScrollPane does not seems to work. 
What's wrong with what I am doing? I post a screen from NetBeans. Thanks.
![istantanea_2016-04-11_23-36-56](https://cloud.githubusercontent.com/assets/11336826/14443576/6678bc8c-0040-11e6-9d25-73e35abee62e.jpg)

**Comment by JordanMartinez** [comment]
@FrancescoTaurino That's because `0.6.10` was released before the skin was removed from RichTextFX (where VirtualFlow was renamed into VirtualizedScrollPane). So, `0.6.10` requires Flowless `0.4.5`, not the snapshot. All the work done since Oct 12, 2015 hasn't been released in a new release but exists in the master branch.
If you want to get everything set up correctly, **download the snapshot versions of ReactFX, Flowless, and RichTextFX** from the OSS Sonatype repository. Then things should work correctly.

**Comment by JordanMartinez** [comment]
If anyone else comes across this problem and is using Gradle, there are a few ways to get this resolved:

Set up the repository to include the OSS repository:
````gradle
repositories {
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}
````
Then there are a few ways to set up the dependencies.
- If only using RichTextFX and not ReactFX or Flowless:
````gradle
dependencies {
    compile group: 'org.fxmisc.richtext', name: 'richtextfx', version: '1.0.0-SNAPSHOT
}
````
- If using RichTextFX and ReactFX but not Flowless or all three, `ReactFX` needs to be excluded since Flowless uses a less recent version of ReactFX (the stable 2.0-Mu4 release) than the snapshot (hence dependency conflicts):
````gradle
dependencies {
    compile group: 'org.reactfx', name: 'reactfx', version: '2.0-SNAPSHOT'
    compile (group: 'org.fxmisc.richtext', name: 'richtextfx', version: '1.0.0-SNAPSHOT') {
        exclude group:'org.reactfx', module: 'reactfx'
    }
}
````

**Comment by FrancescoTaurino** [comment]
@JordanMartinez  thanks for the answer. So:  I downloaded snapshot versions of ReactFX, Flowless, and RichTextFX from the OSS Sonatype repository. I added jars to my project and now VirtualizedScrollPane is ok. But when I compile multiple exceptions are thrown. Is it due to dependency conflict?

**Comment by JordanMartinez** [comment]
@FrancescoTaurino I had to update my first reply to you, but I wasn't sure if you saw it. Yes, there is a dependency conflict between Flowless (uses the 2.0-Mu4 release) and RichTextFX (uses the snapshot release). I don't personally know how to get around that, but I'm sure Googling can help. If not, there's always Gradle :wink:

**Comment by FrancescoTaurino** [comment]
@JordanMartinez sorry, I did not see your second reply! Thank you very much!

**Comment by TomasMikula** [comment]
You can now try out the new 0.7-M1 pre-release.
