### ISSUE TITLE
MouseOverTextEvent over specific word of text

### ISSUE THREAD

**Issue by kushal256** [TomasMikula/RichTextFX#237]
Hi,

Was trying to capture events when the mouse is over certain words of text.  Currently looks like there is a MouseOverTextEvent, which captures the begin and end of when mouse enters a StyledTextAreaView.  Is there anyway to capture when the mouse moves over different words within a StyledTextAreaView?  

Was looking at end of StyledTextAreaView::mouseOverTextEvents(), would the implementation be similar to this method?  Wanted to avoid using addEventHandler(MouseEvent.MOUSE_MOVED, e-> {}) b/c MouseOverTextEvent has the nice mouseOverTextDelay funtionality, so this looks more logical location.

Thanks!

**Comment by TomasMikula** [comment]
Hi,

can't you recover the word from `MouseOverTextEvent#getCharacterIndex()`?

**Comment by kushal256** [comment]
Ah yes, you're right, I can use this.  Was looking for a row+col pair instead of a character index, but I can translate on my own side.  

Thx, will close this.

**Comment by TomasMikula** [comment]
:+1: 

FWIW, I do think we should expose more row+col based API.

**Comment by kushal256** [comment]
How do you want to expose?  

Maybe add to javadoc as an example?  Or could add a cover method (e.g. StyledTextArea::getRowCol(int charIndex) ) that simply does this, so users do not have to think about Bias.Forward, and Position.Major, Position.Minor?

**Comment by JordanMartinez** [comment]
> ...add a cover method (e.g. StyledTextArea::getRowCol(int charIndex) ) that simply does this, so users do not have to think about Bias.Forward, and Position.Major, Position.Minor?

I like that idea because the naming itself is a steeper learning curve than it needs to be.

**Comment by TomasMikula** [comment]
I meant to have versions of methods that take row & column (or `Position`), instead of an absolute index. In many cases this would even be more efficient.
