### ISSUE TITLE
Allow custom implementation of EditableStyledDocument

### ISSUE THREAD

**Issue by JordanMartinez** [TomasMikula/RichTextFX#244]
Tomas originally said in #181
> I eventually want to support custom implementations of what is now called `EditableStyledDocument`....

**Comment by JordanMartinez** [comment]
@TomasMikula 
Do you care to elaborate more on what would be customizeable?

**Comment by TomasMikula** [comment]
My idea is that `EditableStyledDocument` should be an interface, something like

```java
public interface EditableStyledDocument<PS, S> {
    EventStream<RichTextChange<PS, S>> changes();
    ObservableList<Paragraph<PS, S>> getParagraphs();
    ReadOnlyStyledDocument<PS, S> subDocument(Position from, Position to);
    void replace(Position from, Position to, ReadOnlyStyledDocument<PS, S> replacement);
}
```

The implementation can use any represent of a document (e.g. a parse tree), as long as it publishes changes, provides a view as a list of paragraphs, and handles edits.

**Comment by JordanMartinez** [comment]
That sounds good! Should `StyledDocumentBase` be public too then? Additionally, shouldn't the interface also include `EventStream<PlainTextChange> plainTextChanges();`?

**Comment by TomasMikula** [comment]
> Should `StyledDocumentBase` be public too then?

For now I would say no.

> Additionally, shouldn't the interface also include `EventStream<PlainTextChange> plainTextChanges()`?

Yeah, but with a default implementation based on rich text changes. Currently the implementation tries to optimize for the case when plain text changes are observed, but rich text changes are not. The current implementation tries to avoid creating instances of `RichTextChange` at all when no-one is observing them. I don't think the actual savings make any substantial difference, but come with a price of higher complexity of the code.

**Comment by JordanMartinez** [comment]
> Yeah, but with a default implementation based on rich text changes.

Ok.

**Comment by JordanMartinez** [comment]
Just another thought: since there is now an interface for `EditableStyledDocument`, should there be a public interface for its counterpart: `ReadOnlyStyledDocument`? If we're going to allow custom ESD, it seems necessary to do the same for its counterpart.

**Comment by TomasMikula** [comment]
> If we're going to allow custom ESD, it seems necessary to do the same for its counterpart.

Why?

**Comment by JordanMartinez** [comment]
On second thought... I guess that isn't necessary. :-)

**Comment by JordanMartinez** [comment]
This is now technically possible due to #277. However, it is quite a hassle to implement. `EditableStyledDocumentImpl` could be made public temporarily until some better long-term solution is made. This would be easy and quick to implement. However, people might rely on it too much and it might cause problems later on when it's made package-private again and some other long-term approach is implemented. Other thoughts are to make `StyledDocumentBase` public so that the implementation isn't as difficult.

Still, for now, this issue has been resolved and discussions for this new hassle can be discussed in a new issue.
