### ISSUE TITLE
Text that is inserted into an empty StyledTextArea should not inherit deleted style

### ISSUE THREAD

**Issue by JordanMartinez** [TomasMikula/RichTextFX#247]
Taken from #216, here's a summarized version of what  @benedictleejh explained:

When all of the text in a text area is styled, then completely deleted, and then one inserts some new text, the newly-inserted text will inherit the deleted text's style. He proposes that, instead of inheriting the deleted style, it should be styled as `initialStyle`.

**Comment by JordanMartinez** [comment]
@TomasMikula Should this also be fixed before releasing 0.7 ?

**Comment by JordanMartinez** [comment]
Here's the test:
````java
@Test
public void testIfTextInsertionInheritsDeletedStyle() {
    // set up area with some styled text content
    boolean initialStyle = false;
    boolean insertedStyle = true;
    StyledTextAreaModel<String, Boolean> model = new StyledTextAreaModel<>(
            "", initialStyle, new EditableStyledDocument<>("", initialStyle), true);

    // insert text that is styled differently than initialStyle
    model.replace(0, 0, ReadOnlyStyledDocument.fromString("Test", "", insertedStyle));
    // delete all of the area's text
    model.deleteText(0, model.getLength());

    // insert text into area
    model.replaceText("new text");

    // inserted text should not inherit the deleted text's style
    assert initialStyle == model.getStyleAtPosition(0);
}
````

**Comment by TomasMikula** [comment]
I considered this as a feature. For example, that's also what MS Word does (I've just tried it).

I'm open to counter-arguments why it is a bug.

What I consider a bug, though, is that this happens also with undo instead of delete. That is, if I insert some styled text, then undo, then insert (or type in) plain text, the text inherits the style of the "undone" text.

**Comment by JordanMartinez** [comment]
> I considered this as a feature. For example, that's also what MS Word does (I've just tried it).

I agree. I don't see this as a bug itself. 

> I'm open to counter-arguments why it is a bug.

However, I am sure there are also times where such an option might be beneficial ( @benedictleejh probably has one example). So, I think it might be good to add another `BooleanProperty` that determines whether to stick to the default (inherit deleted styles) or not.

> What I consider a bug, though, is that this happens also with undo instead of delete. That is, if I insert some styled text, then undo, then insert (or type in) plain text, the text inherits the style of the "undone" text.

Ah... yeah, that's a bug.

**Comment by benedictleejh** [comment]
I agree it might be useful and helpful in some cases to inherit the deleted style. However, in my case, I'm using the style to hold some properties about the text, so I can style it appropriately (see [here](https://github.com/narrativeandplay/hypedyn2/blob/development/hypedyn-ui/src/main/scala/org/narrativeandplay/hypedyn/dialogs/NodeEditor.scala#L522-L528)).

A property to determine if a deleted style would certainly be appreciated, as while I can workaround it using some [hackery](https://github.com/narrativeandplay/hypedyn2/blob/development/hypedyn-ui/src/main/scala/org/narrativeandplay/hypedyn/dialogs/NodeEditor.scala#L483-L492), it doesn't feel like a particularly nice solution.

**Comment by JordanMartinez** [comment]
In some ways, your suggestion seems similar to #209. 

> A property to determine if a deleted style would certainly be appreciated..

Are you suggesting that, if some text is inserted at some point, there would be a property (or perhaps a query) that would indicate whether this inserted text would inherit the deleted style as opposed to being styled with `initialTextStyle`?

**Comment by benedictleejh** [comment]
In some ways, #209 does seem similar, though I'm mostly concerned with new text being inserted after old text has been deleted.

> Are you suggesting that, if some text is inserted at some point, there would be a property (or perhaps a query) that would indicate whether this inserted text would inherit the deleted style as opposed to being styled with `initialTextStyle`?

Yes, that sounds about right. Though it seems only applicable when dealing with an empty text area, as normal insertion simply inherits the style of the text just before it.

**Comment by JordanMartinez** [comment]
> Though it seems only applicable when dealing with an empty text area, as normal insertion simply inherits the style of the text just before it.

If that's the case, couldn't you just write some method does something like this:

````java
public void insertSpecialText(int start, int end, String text) {
    if (length() == 0) {
        replace(start, end, ReadOnlyStyledDocument.fromString(text, initialParagraphStyle, initialTextStyle);
    } else {
        replaceText(start, end, text);
    }
}
````

**Comment by TomasMikula** [comment]
I fixed the part of this issue that I considered a bug.

As Jordan suggested, if you want the inserted text to have a specific style (instead of inheriting whatever style was there before), you can use `replace(from, to, StyledDocument)` instead of `replaceText(from, to, String)`. Testing the length in Jordan's code is not even necessary, since the `replace` method works in all cases.

As a result, I'm closing this issue.
