### ISSUE TITLE
[SNAPSHOT] Regression: mouse cursor is no longer styled as TEXT

### ISSUE THREAD

**Issue by kuc** [TomasMikula/RichTextFX#258]
In `0.6.10`, mouse cursor was set to `TEXT` on `VirtualFlowContent` node.
In `SNAPSHOT`, `VirtualFlowContent` node is no longer used and no one of other nodes have any styling for mouse cursor, so default (pointer) cursor is used.

**Comment by JordanMartinez** [comment]
Could you provide a working example of the problem?

**Comment by kuc** [comment]
Screenshot form ScenicView
![image](https://cloud.githubusercontent.com/assets/1827393/13184903/cf05cd7e-d73e-11e5-8b4d-f6c70a02b6be.png)

Cursor is set to default, despite [rules from `styled-text-area.css` file](https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx/src/main/resources/org/fxmisc/richtext/styled-text-area.css)

**Comment by kuc** [comment]
If that will help you to investigate this problem, I tried setting that rule again from custom CSS and it worked. But it should work out of the box :confused:

**Comment by TomasMikula** [comment]
We lost [this line](https://github.com/TomasMikula/RichTextFX/blob/5ca21a26b55b583a490d5280778a0c4c69a19a56/richtextfx/src/main/java/org/fxmisc/richtext/skin/StyledTextAreaView.java#L115) somewhere in the process of refactoring.

**Comment by JordanMartinez** [comment]
> We lost this line somewhere in the process of refactoring.

My bad... That probably happened in the skin-removal commits (as I didn't quite get how CSS stuff worked by that point).

**Comment by JordanMartinez** [comment]
Yup. The regression is introduced in c465cf5d3ab49fa6d0f05559b413a417c9c8779c
I didn't copy the code exactly for Line 521 and it's hard to notice the error since the class content of `StyledTextAreaView` was being copied into `StyledTextArea` (Git doesn't clearly show where the copying differs from another file unfortunately...)

**Comment by TomasMikula** [comment]
Don't worry, things like this are easy to miss. Thanks @kuc for reporting!
