### ISSUE TITLE
Bind to text empty

### ISSUE THREAD

**Issue by EMostafaAli** [TomasMikula/RichTextFX#264]
In text area, we are able to write code like this:
`OkButton.disableProperty().bind(Bindings.isEmpty(textArea.textProperty()));`

Is this possible through CodeArea?

**Comment by TomasMikula** [comment]
Yes, it is possible, though this exact same code will not work. (`Bindings.isEmpty` expects an `ObservableStringValue`, which `StyledTextArea.textProperty` is not.) You can, for example, do

```java
OkButton.disableProperty().bind(Val.map(textArea.lengthProperty(), n -> n == 0));
```

where [`Val.map`](http://www.reactfx.org/javadoc/2.0-M4u1/org/reactfx/value/Val.html#map-javafx.beans.value.ObservableValue-java.util.function.Function-) is from ReactFX.
