### ISSUE TITLE
Move caret position in StyleTextArea by line number

### ISSUE THREAD

**Issue by firm1** [TomasMikula/RichTextFX#286]
Hello,

I don't know if it's handle correctly, but i can't move caret position with line number like parameter.

I would like use something like `textarea.positionCaret(int row)`, but the only param avalaible is number of characters. 

I found and tried this solution without success: 

```java
textarea.selectRange()
```

```java
textarea.position(row, col)
```

```java
textarea.positionCaret()
```

Somebody can tell me how i can do for solve my problem ?

**Comment by JordanMartinez** [comment]
There's currently no API that does what you want efficiently.

Since the caret can only be set via an actual character position, the following code will work but it's inefficient. It'd be better to implement a method specifically for this, such as `StyledTextAreaModel#positionCaret(int row, int col)`:
````java
public void positionCaret(StyledTextArea<?, ?> area, int row, int col) {
    if (
            // ensure valid range for row
            (0 <= row && row <= area.getParagraphs().size()) &&
            // ensure valid range for col
            (0 <= col && col <= area.getParagraph(row).length())
    ) {
        int position = 0;
        for (Paragraph par : area.getParagraphs().subList(0, row)) {
            position += par.length() + 1; // account for line terminators
        }
        // now add the column
        area.positionCaret(position + col);
    }
}
````

**Comment by TomasMikula** [comment]
I agree it would be both easier and more efficient to have a direct API for that.

For now, you can still do it somewhat simpler than what was suggested:

```java
area.positionCaret(area.position(row, 0).toOffset());
```

**Comment by firm1** [comment]
Thanks @TomasMikula for the workaround it's work fine for me.
