### ISSUE TITLE
InlineCssTextArea paragraph style

### ISSUE THREAD

**Issue by FrancescoTaurino** [TomasMikula/RichTextFX#289]
Hi,
Please excuse me for opening another issue, but I need help.

I am using `InlineCssTextArea` and I would like to highlight the current line, i.e. where the caret is.
I tried this option, but it doesn't seem to work:
```
area.caretPositionProperty().addListener(e -> {
	newCurrentLine = area.getCurrentParagraph();
	if(newCurrentLine != oldCurrentLine) {				
		area.setParagraphStyle(oldCurrentLine, "-fx-background-color: #FFFFFF;");
		area.setParagraphStyle(newCurrentLine, "-fx-background-color: #F2F2F2;");
				
		oldCurrentLine = newCurrentLine;
	}
});
```

`oldCurrentLine` and `newCurrentLine` are int.

The idea is to color the new current line and to set white the old one, but background remains always white and it does not change. What's wrong with what I am doing? 

Thanks in advance.

**Comment by TomasMikula** [comment]
Hi,

not sure why it doesn't work, but if you try the current [snapshot version](https://github.com/TomasMikula/RichTextFX/#snapshot-releases), you can use the `:has-caret` pseudo class in CSS stylesheet to set style of the current line. The `JavaKeywords` demo [does that](https://github.com/TomasMikula/RichTextFX/blob/2b4ba4378cfe27facfd86051771946ed9c0dc691/richtextfx-demos/src/main/resources/org/fxmisc/richtext/demo/java-keywords.css#L28-L30) now.

**Comment by FrancescoTaurino** [comment]
Thanks Thomas, using:
```
.paragraph-box:has-caret {
    -fx-background-color: #f2f2f2;
}
```
all the work is done. 
Thank you very much, I hope this can be helpful for someone else.
