### ISSUE TITLE
Modify font type in StyleClassedTextArea

### ISSUE THREAD

**Issue by WinXaito** [TomasMikula/RichTextFX#290]
Hello guys,

`Sorry for my bad English, I speak French`

I would like to change the type of writing in a `styleClass textarea`, but only the size change by doing something like this:

```java
SourceText.setFont(new Font("Font name", 10));
```

Only the size is considered. Is this normal? Is editable?

**Comment by WinXaito** [comment]
Oh I'm sorry, it's because i've had a font in my CSS. It's good !

**Comment by JordanMartinez** [comment]
:smile: No worries!

**Comment by WinXaito** [comment]
I still want to tell you, it's cool to use a library like this with quick support, because we've needed!
