### ISSUE TITLE
Background on a text

### ISSUE THREAD

**Issue by WinXaito** [TomasMikula/RichTextFX#295]
Hello,

I managed to shed fat and add a color on a piece of text in my `StyleClassedTextArea`, but I would love to put a `background`, but it does not work. Is it possible to do this?

Thank you !

**Comment by TomasMikula** [comment]
Yes, it is possible:

```css
.foo {
    -fx-background-fill: #efefef;
}
```

It is named `-fx-background-fill` instead of `-fx-background-color` because of this bug: [JDK-8133685](https://bugs.openjdk.java.net/browse/JDK-8133685).

**Comment by WinXaito** [comment]
Thanks ;)

**Comment by swpalmer** [comment]
Is it possible to set the background colour for the entire line - such that the colour extends all the way to the edge of the view, even if the text doesn't?
I.e. so we don't get ragged edges on the background for areas of the text like this:
short line<--- background colour ends here
a much longer line<--- background colour ends here

I want to mark the entire line with a different background colour to highlight special cases, like lines with errors, or sections of file that were inserted or removed , commented out sections etc.

**Comment by TomasMikula** [comment]
It is possible with the snapshot release, where, in addition to setting style for a range of text, you can set style for the whole paragraph ([setParagraphStyle](https://github.com/TomasMikula/RichTextFX/blob/da2fd32f218a62ec7cbd80d9d691a67b702ed00d/richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java#L942)).
