### ISSUE TITLE
Use of StyleSpans.subView, and replacing StyleSpans at certain positions

### ISSUE THREAD

**Issue by radicaled** [TomasMikula/RichTextFX#301]
So, let's say I'm using a `StyleClassedTextArea`, and I want to change the background color of the user's current focus, based on where their caret is at the moment. I'm also doing other manipulations, so I have a function that receives a `StyleSpans<Collection<String>>` and is also expected to return a `StyleSpans<Collection<String>>` with the correct styles applied to it. This way, I can avoid multiple `setStyle` calls and just do it once after every processor adds or removes classes as necessary.

I'm using `StyleSpans.subView(...)` to scope my class additions / subtractions to a small range, but I'm not sure how to merge my changes back into the main collection after I've used `mapStyles` or `overlay` on the `StyleSpans` returned from the "master" `StyleSpans.subView`.

Here's some pseudo-code written in Kotlin if I'm not clear enough.

```kotlin
// Where's the caret at?
val indexRange = getCurrentParagraphBasedOnEvilWizardry(textArea.selection)
// Get all the style spans in the document
val styleSpans = textArea.getStyleSpans(0, textArea.length - 1)
// Remove old "focused" styling, because the user might not be on the same line anymore
val withoutFocus = styleSpans.mapStyles { /* removes "focused" class from each collection */ }
// OK, now I have a StyleSpan collection that no longer includes the "focused" class.
// Let's get a subview containing just the stylespans that exist in indexRange.
val subview = withoutFocus.subView(indexRange.start, indexRange.end)
// OK, now let's add the "focused" style.
val newStyle = StyleSpans.singleton(/* ... */)
val withFocusSubview = subview.overlay(newStyle) { theirs, ours -> (theirs + ours) }
// OK, now we've got a StyleSpans that all have the "focused" class in them.
// Now we need to go back to withoutFocus, and replace the stylespans contained within indexRange with the new ones.
// Nonexistant method.
return withoutFocus.replace(indexRange.start, indexRange.end, withFocusSubview); 
```

I'm trying to avoid multiple calls to `setStyle` and having other components know about the textarea.

**Comment by TomasMikula** [comment]
You could do two more sub-views, before and after the "focused" sub-view, and then `concat` all three together.

In case you are using the SNAPSHOT version, you can style the whole paragraph using the `:has-caret` pseudo class, like [here](https://github.com/TomasMikula/RichTextFX/blob/2b4ba4378cfe27facfd86051771946ed9c0dc691/richtextfx-demos/src/main/resources/org/fxmisc/richtext/demo/java-keywords.css#L28).

**Comment by radicaled** [comment]
Thanks. The `:has-caret` class might be what I need, but I'm on 0.6.10 for now. Is there also a way to style the background of paragraphs themselves in SNAPSHOT?

**Comment by TomasMikula** [comment]
Yes. `StyledTextArea`, `Paragraph`, etc. are parameterized by an additional type parameter, `PS`, representing the paragraph style.

**Comment by radicaled** [comment]
Thanks (again!). Looks like I need to upgrade to the SNAPSHOT version to clean up my solutions.
