### ISSUE TITLE
Expose a "constructor" for EditableStyledDocumentImpl in its interface

### ISSUE THREAD

**Issue by JordanMartinez** [TomasMikula/RichTextFX#308]
Slightly related to #278, but could we add a static method to `EditableStyledDocument` that returns back an instance of `EditableStyledDocumentImpl`?

In my project, I'm creating the model first and then passing that to the view to display. My view has multiple components to it, one of which is a `StyledTextArea`. Since I don't have my own custom implementation of `EditableStyledDocument`, I currently have to create a fake `StyledTextArea` just to get an instance of the implementation class via `StyledTextArea#getContent`. Once the model has been fully constructed, I then pass it to the view which creates one or more areas that share that document.

**Comment by TomasMikula** [comment]
Being able to create an `EditableStyledDocument` without creating a `StyledTextArea` sounds reasonable. Maybe I would even make the class public, but rename it to e.g. `SimpleEditableStyledDocument`.

**Comment by JordanMartinez** [comment]
Why make it public though? You seemed to be against that beforehand.

**Comment by TomasMikula** [comment]
I think I was mainly against it serving as a base class for custom `EditableStyledDocument` implementations that users would inherit from. I still hold that position, and the class is indeed final.

**Comment by JordanMartinez** [comment]
Resolved by #309
