### ISSUE TITLE
Flowless issue: Scrollbars' height/length need to be longer

### ISSUE THREAD

**Issue by JordanMartinez** [TomasMikula/RichTextFX#312]
Using the latest snapshot, both scrollbars can be scrolled but it won't affect the display of the content when scrolled downward/rightward after a certain point. In other words, the vertical scrollbar's height and the horizontal scrollbar's length is too short and should be longer.

Note: the below gif only shows the issue with the vertical scrollbar

![unneededscrollbarspace](https://cloud.githubusercontent.com/assets/8413037/15304232/ff62fef8-1b70-11e6-9ebe-56d58a9471a2.gif)

**Comment by TomasMikula** [comment]
Yup, this is what I meant in [this comment](https://github.com/TomasMikula/RichTextFX/issues/311#issuecomment-219308666). I broke it in [this commit](https://github.com/TomasMikula/Flowless/commit/842ae709cdbc84297235fe8e5bfddd54dedfdb8a). I just naively removed scrollbar position calculations from `VirtualFlow` (because they simply don't belong there), while I should have moved that to `VirtualizedScrollPane`. I will fix that ;)

**Comment by JordanMartinez** [comment]
I was wondering if that was related in some way. :-)

**Comment by TomasMikula** [comment]
Should be all good now, just make sure to re-download Flowless.

**Comment by JordanMartinez** [comment]
When I locally compile Flowless and make that the dependency rather than the 0.6-snapshot, it does work. So, did you not release a new snapshot?

**Comment by TomasMikula** [comment]
I believe I did. Will redo just in case. Sometimes I need to wipe gradle cache (contents of my `.gradle` folder) to force a re-download.

**Comment by JordanMartinez** [comment]
I wiped my gradle cache and cleaned the gradle directory but the issue still appears. Not sure why...

**Comment by TomasMikula** [comment]
Have you also tried what @swpalmer suggested [here](https://github.com/TomasMikula/RichTextFX/issues/307#issuecomment-219705106)?

**Comment by JordanMartinez** [comment]
Just did. Still no difference.

**Comment by JordanMartinez** [comment]
Fixed it. [@Crystark's comment](https://github.com/TomasMikula/RichTextFX/issues/307#issuecomment-219997256) made me wonder if I had updated the OSS repository cache in my IDE. Once updated, the problem disappeared.

**Comment by TomasMikula** [comment]
Glad that you were able to resolve it.
