### ISSUE TITLE
Dotted underline 

### ISSUE THREAD

**Issue by RodrigoSantiago** [TomasMikula/RichTextFX#316]
I've tried using CSS in many ways but it still fails. My goal is to put underline in texts written with an error

**Comment by afester** [comment]
I could be wrong, but I think this is not supported yet. Each text segment is made up of a JavaFX `Text` node and a `Path` node for the background - both do not support a border. 

The background shape is not necessarily a rectangular area (if the text is wrapped). So it must be a Path with arbitrary coordinates. Simply using a `Region` (which supports borders) instead does not work. It might be possible to calculate the coordinates of the corresponding bottom lines from the `PathElements` array returned from `TextLayout.getRange()` - the second and third LineTo contain the required coordinates. With that information, it should be possible to add another `Path` to add a bottom line to each text segment. That depends on the (currently non-public) `TextLayout`-API though.

**Comment by TomasMikula** [comment]
@RodrigoSantiago you can try it out if you download a fresh SNAPSHOT version. See #317 for the available CSS properties.

**Comment by JordanMartinez** [comment]
I've updated the RichTextFX CSS Reference Guide to include the new CSS properties.

**Comment by TomasMikula** [comment]
Cool, thanks!

**Comment by TomasMikula** [comment]
Part of 0.7-M2.
