### ISSUE TITLE
Execute some code after ENTER Key pressed

### ISSUE THREAD

**Issue by firm1** [TomasMikula/RichTextFX#319]
Hi,

What is the best way with RichtexFx to execute some code after ENTER Key ? I use `0.6.10` release.

I want if possible override [this line](https://github.com/TomasMikula/RichTextFX/blob/2ac5b74a4154953139268fbb30df42ab65ab2e37/richtextfx/src/main/java/org/fxmisc/richtext/StyledTextAreaBehavior.java#L69) for example, but i don't know how i can do that.

Can you explain me please ?

**Comment by TomasMikula** [comment]
Hi,

if you are using 0.6.10, you actually need to look at [this version](https://github.com/TomasMikula/RichTextFX/blob/3d37aa19b0f3e2f171dafb7a500f2dee122e394c/richtextfx/src/main/java/org/fxmisc/richtext/StyledTextAreaBehavior.java#L72) of the file, which uses an older version of WellBehavedFX.

You will need to do something like this:

```java
// define the event handler
EventHandler<KeyEvent> handler = EventHandlerHelper
        .on(keyPressed(ENTER)).act(e -> { /* code to execute on Enter goes here */ })
        .create();

// install the event handler
EventHandlerHelper.install(area.onKeyPressedProperty());
```

**Comment by firm1** [comment]
Thank for answer.

But this code override the Enter key behavior. I just need to add something
after existing behavior, not rewrite.

**Comment by TomasMikula** [comment]
The most reliable way is to first replicate in your handler whatever `StyledTextAreaBehavior` does, i.e. `area.replaceSelection("\n")`:

```java
EventHandler<KeyEvent> handler = EventHandlerHelper
        .on(keyPressed(ENTER)).act(e -> {
                area.replaceSelection("\n");
                /* your code goes here */
        })
        .create();
```

**Comment by TomasMikula** [comment]
You could also just try using the usual `area.addEventHandler(KeyEvent.KEY_PRESSED, e -> { ... })`, but there is no guarantee that this will be called _after_ the default handler.

**Comment by firm1** [comment]
Ok thanks for your advice.

It's ok for me
