### ISSUE TITLE
Update RTFX-specific CSS to use project-specific prefix

### ISSUE THREAD

**Issue by JordanMartinez** [TomasMikula/RichTextFX#323]
Coming from #317, we should change the CSS that RichTextFX adds to use the prefix `-rtfx-` instead of `-fx-`. For reference, see [Naming of CSS property names for JavaFX](https://stackoverflow.com/questions/36725475/naming-of-css-property-names-for-javafx)

**Comment by TomasMikula** [comment]
Resolved by #324, #325
