### ISSUE TITLE
Programmatically select text

### ISSUE THREAD

**Issue by ostfale** [TomasMikula/RichTextFX#329]
I have some formatted text which consists of variables at fixed position. I can select the variables (combobox)  and want to show (select) them in the text.  I can jump to the right line / column. But if I call selectRange it highlights text in the first line. 

Thx for help, regards, Uwe

**Comment by TomasMikula** [comment]
Hi, `selectRange` expects absolute positions. Are you calling it with absolute positions?

If you have

```java
int startRow;
int startCol;
int endRow;
int endCol;
```

you can convert them to absolute positions like this:

```java
int startPos = area.position(startRow, startCol).toOffset();
int endPos = area.position(endRow, endCol).toOffset();
area.selectRange(startPos, endPos);
```

**Comment by ostfale** [comment]
That's exactly the solution! Thanks...

**Comment by TomasMikula** [comment]
There are now convenience methods taking row/col coordinates in the snapshot release thanks to @JordanMartinez via #331.
