### ISSUE TITLE
Character index inside Drag&Drop event handler

### ISSUE THREAD

**Issue by ArdakSaduakassov** [TomasMikula/RichTextFX#335]
How to get character index by mouse coordinates inside Drag&Drop event handler?
I need to drop a visual component onto a CodeArea and insert some text at arbitrary position. Is there any utility method to convert screen coordinates to character index? Or could you please implement such method in a future release?

**Comment by JordanMartinez** [comment]
> Is there any utility method to convert screen coordinates to character index?

Yes, see `hit(double mouseX, double mouseY)`

**Comment by ArdakSaduakassov** [comment]
It works like a charm! Thank you for the quick reply.
