### ISSUE TITLE
Not usable within SWT (eclipse)

### ISSUE THREAD

**Issue by rivagti** [TomasMikula/RichTextFX#336]
Control is not working as expected within FXCanvas, which is used as container for eclipse plugin editor.
Problem is, that typing any keys works, but I'm not able to insert/delete any character using Enter/Delete/Ctrl+V keys... Another FX controls (like TextArea) are working well.

**Comment by TomasMikula** [comment]
Hi, character input is implemented via `KEY_TYPED` events, the others you mention via `KEY_PRESSED` events. Some parent is probably blocking `KEY_PRESSED` events to be delivered to the text area.

**Comment by TomasMikula** [comment]
Have you figured out what was preventing the `KEY_PRESSED` events to be delivered to the text area?
