### ISSUE TITLE
Matching Bracket/Brace/Paren Highlight

### ISSUE THREAD

**Issue by Ansury** [TomasMikula/RichTextFX#337]
Enhancement suggestion: 
Highlight the closing character for Bracket/Brace/Paren blocks in code (ex. red box outline around the opposite character).

![screenshot from 2016-07-07 01 00 18](https://cloud.githubusercontent.com/assets/11338660/16642981/464513a2-43de-11e6-8aad-6f152cb28269.png)

**Comment by Ansury** [comment]
So, if I were to try implementing such a feature (first of all, would it even be welcome?), is there any specific strategy I should be looking at?  This goes for the other feature request I've added.

**Comment by JordanMartinez** [comment]
> would it even be welcome?

If implemented directly on `CodeArea`, probably not. This project is intended to serve as a base on which others (such as yourself) can build new features (such as the block highlighting).

However, if you wrote an example in the demos package that does what you propose, that would be accepted as an example for others to follow if they desire the same thing.

At the same time, if you see #275, you'll see that Tomas would be greatly interested in one who would build a fully-featured code area on top of this project

**Comment by JordanMartinez** [comment]
>  is there any specific strategy I should be looking at?

Tomas would have a better understanding for how to do this. I'll give you my take for now. No doubt you should style the block/parent with a style class specific to that:
- Wherever the caret is moved to a new position
 - check if previous position caused the highlighting of an open/closing block/parent
 - if so, remove the style class from those two characters
 - get that character next to the caret's new position
 - check if it's one of your valid characters
 - if so, find its corresponding closing block/paren's position & style both opening/closing characters with a style class

**Comment by JordanMartinez** [comment]
After reading your original comment again, there's one last thing worth sharing. I don't think there is currently a way to create a red (or some other colored) box around a character(s). See the [RichTextFX CSS Reference Guide](https://github.com/TomasMikula/RichTextFX/wiki/Styling-RichTextFX-and-a-CSS-Cheat-Sheet)

**Comment by TomasMikula** [comment]
I share Jordan's opinion that this is not something that should be directly supported by `RichTextFX`, but we would welcome a demo that shows how to implement that.

The exact style you have in your screenshot (rectangular outline) is not currently possible, but you could just use background color instead. We would also welcome contribution that adds the outline styling. This would be similar to adding background color (#166) and underline (#317).

**Comment by JordanMartinez** [comment]
Closing as its outside the scope of this project.
