### ISSUE TITLE
Highlight matching words in code (background color)

### ISSUE THREAD

**Issue by Ansury** [TomasMikula/RichTextFX#338]
(Enhancement suggestion) 
Eclipse example: 

![screenshot from 2016-07-07 01 03 19](https://cloud.githubusercontent.com/assets/11338660/16643030/c57a50ce-43de-11e6-90a8-64212f49ca81.png)

**Comment by TomasMikula** [comment]
I think highlighting based on string matching has very limited benefits for a code editor. I think it is only really useful if highlighting is done based on some semantic representation of the source code, such as [abstract semantic graph](https://en.wikipedia.org/wiki/Abstract_semantic_graph). What do you think?

**Comment by Ansury** [comment]
Well, I think I see where you're going here.  (ANTLR etc?)  Certainly that'd be more useful, but I think that's a little too large of a distraction for me at the moment.

**Comment by Groostav** [comment]
Worth mentioning, I implemented this, but never got the build system ship-shape:
https://github.com/EmpowerOperations/ANTextFX

I'll work on updating the readme and samples this weekend --but it does require you to supply an ANTLR parser and lexer.

**Comment by JordanMartinez** [comment]
Closing as this is outside the scope of the project. 
Please reopen if you think otherwise.
