### ISSUE TITLE
Styles are not applyed to Text

### ISSUE THREAD

**Issue by Samyssmile** [TomasMikula/RichTextFX#340]
@FXML
    void onBold(ActionEvent event) {
        
        IndexRange ir = sctTextEditor.getSelection();
    
        ArrayList<String> styles = new ArrayList<>();
        styles.add("-fx-font-weight: bold");
        sctTextEditor.setStyle(ir.getStart(), ir.getEnd(), styles);
}

This code not working, is this a issue or my mistake?

**Comment by TomasMikula** [comment]
Hi, judging by the fact that you are using an `ArrayList<String>` as your style, I assume that you are using `StyledClassedTextArea` or its subclass (e.g. `CodeArea`). This kind of text area expects the strings to be names of CSS _style classes_ that you then refer to from your CSS file. For example:

In Java:

```java
area.setStyle(from, to, Arrays.asList("bold"));
```

In CSS:

```css
.bold {
    -fx-font-weight: bold;
}
```
