### ISSUE TITLE
0.7-M1 has duplicate versions of reactfx

### ISSUE THREAD

**Issue by effad** [TomasMikula/RichTextFX#341]
reactfx is included twice in different versions.
2.0-M5 comes directly from richtextfx (and from flowless)
2.0-M4u1 comes from undofx:1.2

compile - Compile classpath for source set 'main'.
\--- org.fxmisc.richtext:richtextfx:0.7-M1
     +--- org.fxmisc.wellbehaved:wellbehavedfx:0.3
     +--- org.fxmisc.flowless:flowless:0.5
     |    \--- org.reactfx:reactfx:2.0-M5
     +--- org.fxmisc.undo:undofx:1.2
     |    \--- org.reactfx:reactfx:2.0-M4u1 -> 2.0-M5
     \--- org.reactfx:reactfx:2.0-M5

**Comment by TomasMikula** [comment]
Thanks for reporting, I will make an update release of UndoFX and RichTextFX. Hopefully this didn't cause any real trouble, since UndoFX should work with ReactFX 2.0-M5 just as well.

**Comment by TomasMikula** [comment]
Resolved in 0.7-M2.
