### ISSUE TITLE
Change to -fx-font-size for CodeArea make scroll bigger

### ISSUE THREAD

**Issue by zburguy** [TomasMikula/RichTextFX#344]
@FXML public CodeArea textArea;
...
textArea.setStyle("-fx-font-size:32px");

Can you please tell how to change the font size without changing the size of the scroll?

![2016-07-22_13-14-48](https://cloud.githubusercontent.com/assets/710786/17054159/58281ef2-500e-11e6-8c0e-8a66c379455f.png)

**Comment by JordanMartinez** [comment]
Which release are you using?

**Comment by zburguy** [comment]
I use 0.6.10 and 0.7-M2 - identical behavior.
