### ISSUE TITLE
Add support for a border around some text

### ISSUE THREAD

**Issue by NavalOrange** [TomasMikula/RichTextFX#346]
Hey there, I was wondering if there was a nice way to get a border for a highlight area in a StyleClassedTextArea. And if not I would like to make a feature request : D.

Something similar to what I'm looking for is the name change indicator in IntelliJ.
![intellijhighlightborder](https://cloud.githubusercontent.com/assets/1515071/17426660/d526949e-5a8e-11e6-84cf-99811b9398eb.png)

Specifically what I was looking to do is highlight locations in a text file based on user inputted row, column and lengths. For most of the use cases just having a colored background is fine. However, in the event that the user inputs a zero length location, there is nothing to highlight. With a border around a zero width selection, there would be feedback for the user.

In IntelliJ, it looks like this:
![intellijhighlightborder2](https://cloud.githubusercontent.com/assets/1515071/17426754/b9805bfc-5a8f-11e6-8ce5-95b75411a43c.png)

Thanks for the help!

**Comment by JordanMartinez** [comment]
> I was wondering if there was a nice way to get a border for a highlight area in a StyleClassedTextArea. And if not I would like to make a feature request : D.

Currently, there is not a way to do that. Something similar was already asked in #337 (see the comments after the initial issue).

**Comment by NavalOrange** [comment]
Aaah sorry about that, thanks for the info!

**Comment by JordanMartinez** [comment]
@NavalOrange This is possible with #455, but it still wouldn't be the best way to do it.

**Comment by JordanMartinez** [comment]
This is slightly outside the scope of this issue, but I've been wondering whether the entire style handling for rich text should be completely refactored. As pointed out [here](https://github.com/TomasMikula/RichTextFX/pull/497#issuecomment-298988944) and originally [here](https://github.com/TomasMikula/RichTextFX/pull/166#issuecomment-131957896), there is a white (or same color as background) line that appears when two texts share the same background color but not the same style, resulting in 2+ background shapes being used for that background color.
By following the same approach we are currently using (each Text segment gets its own background shape), this break continues to occur now and will show up when the border text feature is implemented.

So, I'm wondering whether we could apply styles in a different ways. For example, style that apply only to the text (its size, its fill color, etc.) should be extracted from the style object and applied to that text. However, styles that apply to things behind/around the text (background color, underline, border around the text) should be handled separately by `ParagraphText` (or perhaps `TextFlowExt`).

In other words, only one background shape would be created for 4 text segments that all share the same background, even if they share different fill styles. However, this approach would need to factor in the possibility of a text segment spanning across multiple lines (in the case of line wrap being on). In other words, the code would need to:
1. Calculate the span of shared background-like styles
2. Split these spans into line-specific spans (if `wrapText` is true)
3. Create a background shape object for each line-specific span and set it behind a line's text.

The border text feature would need to add an additional step to the above. In situations where a border spans multiple lines, the first line should not have a closing right side:
````
// line 1
---------
| text     (no right bound)
---------
// line 2
---------
 text     (no right/left bound, only top/bottom)
---------
// line 3
---------
 text   | (no left bound)
---------
