### ISSUE TITLE
CodeArea styling issue

### ISSUE THREAD

**Issue by jtrunick** [TomasMikula/RichTextFX#347]
I set my CodeArea background color to black, this means that I'm typing "in the dark" until my highlighting logic catches up. I'm borrowing very heavily from the Async example.

I added this so that the text will show up as something visible right away:
```
.styled-text-area .text {
    -fx-fill: purple;
}
```

However, now the problem is that my StyleSpans for color is being overriden by this one. I'm not savvy enough to figure out how to fix this by somehow tweaking the passed in styling classes to be more specific. How should I address this?

**Comment by TomasMikula** [comment]
Hi, if your style class is `highlight`, then this should do it:

```css
.styled-text-area .text.highlight {
    -fx-fill: yellow;
}
```

Note the lack of whitespace between `.text` and `.highlight`.

**Comment by jtrunick** [comment]
awesome, great, that worked.
