### ISSUE TITLE
Dual-license: check comply 

### ISSUE THREAD

**Issue by nsavageJVM** [TomasMikula/RichTextFX#351]
Hi I am using this code as a module in the source  in another opensource project [here](https://github.com/nsavageJVM/logcat-utls)  
I display the [license](https://github.com/nsavageJVM/logcat-utls/tree/master/richtextfx) in the module and make the source available as well as point to this repo in the readme  
If any issues exist you can let me know here and I will comply. Thanks for this.

**Comment by kuc** [comment]
You are using RichTextFX only as dependency, so why are you commited it's whole source code to your repo, instead of just adding
```
dependencies {
    compile group: 'org.fxmisc.richtext', name: 'richtextfx', version: '0.7-M2'
}
```
to `gradle.build` file? 😕

**Comment by nsavageJVM** [comment]
Hi, I made some small changes to the source, I cant remember exactly now as its been a while since I have looked at the code

**Comment by TomasMikula** [comment]
Hi. Yeah, that's fine. Dual-licensed means you can pick the license that better suits your needs.

Aside, though, maintaining your own fork might come at a cost.
