### ISSUE TITLE
Support embedding arbitary nodes like Hyperlinks and ImageView in text layout

### ISSUE THREAD

**Issue by sco0ter** [TomasMikula/RichTextFX#355]
Hi,

I need something similar to `javafx.scene.text.TextFlow`, where you can put HyperLinks and ImageViews as well (or any arbitrary Node), BUT unlike TextFlow, the Text (and maybe even HyperLinks) should be selectable (for copying the selected text).

Something like:
http://www.java-blog-buch.de/wp-content/uploads/2009/08/000073.png
(See the image on the bottom)

Think of a chat window with smileys and hyperlinks and probably other nodes embedded in the text layout.

It seems like Swing allows that (at least using images within text) using `javax.swing.JTextPane` + `javax.swing.text.StyledDocument`

I've looked at RichTextFX, but it seems you can only use plain text, but not embed other nodes in the text layout, right?

Anybody could point me in a direction, where to look and what to do, if I have to do it myself?

**Comment by JordanMartinez** [comment]
Right. It only uses plain or rich text, but embedding other nodes is not currently supported (though I'm sure many want such a feature). You're not the first person to ask about inserting an arbitrary node. However, I think selecting it and copying/pasting it is a new request.

Have you already checked out #87? It's very similar to what you're requesting and Tomas has already stated something there.

**Comment by TomasMikula** [comment]
Btw, you can have hyperlinks (since they can be just styled `Text` nodes with an `onMouseClicked` action), see #124 for an example.

Regarding arbitrary nodes, I would like to support that feature, but haven't thought too hard what would be the best way to implement it and (most importantly) what the API would look like.

Copying my comment from #314, which was @afester's take on custom objects:

> Just a general remark: I am a big fan of type safety, so I would like to explore some generic approach that avoids runtime `instanceof` checks, or rules out the possibility (at compile time) that we get an object type that we don't know how to render.

**Comment by afester** [comment]
I have prepared a new iteration of my earlier proposal to support any custom node objects (will shortly submit the pull request). You can review the current state at https://github.com/afester/RichTextFX/tree/customObject. It also supports copy&paste, but it does not yet support direct selection of custom nodes by clicking on them (but I already have that in mind).

**Comment by afester** [comment]
Fixed with #356. See the rich text editor demo how to add inline images. Hyperlinks require a little more work but should also be feasible now.
