### ISSUE TITLE
Meta: Add Kanban-style (Trello) boards?

### ISSUE THREAD

**Issue by JordanMartinez** [TomasMikula/RichTextFX#359]
Via [this link about GitHub's new features](https://techcrunch.com/2016/09/14/github-gets-built-in-project-management-tools-and-support-for-reviews/amp/), could we add a Trello-like board to this project to do things like:
- give a "roadmap" idea of where its going
- give a difficulty rating to various features we would like to implement in the future (regardless of who does the work)

**Comment by TomasMikula** [comment]
Yes :)

**Comment by JordanMartinez** [comment]
Excellent!

Since I'm not sure how most developers will respond to / interact with this new GitHub feature, I'm not sure if this should take the place of the small section in the ReadMe that describes ways to help / lists desired feature requests. It does make things much more clear (and is probably easier to update) without spamming the project's commit history with minor ReadMe-updating commits. 
At the same time, are people going to think to check that first?

**Comment by TomasMikula** [comment]
We will see :)

**Comment by JordanMartinez** [comment]
@TomasMikula Just FYI, the Project board [like this one](https://github.com/TomasMikula/RichTextFX/projects/3) unfortunately does not remove issues once they have been closed.

**Comment by TomasMikula** [comment]
Thanks for pointing that out. Yeah, the project board functionality is somewhat limited.
