### ISSUE TITLE
Image Info next to the lines

### ISSUE THREAD

**Issue by GweltazCalori** [TomasMikula/RichTextFX#360]
Hi,
I wanted to know if it's possible to have image info next to line numbers. For example in Intellij you can have an info next to the line.
![intel](https://cloud.githubusercontent.com/assets/12122821/18617493/f21a5940-7dd0-11e6-823f-3cdfc777f6ec.PNG)

I used LineNumberFactory to add line but I can't find abything about adding infos.

**Comment by TomasMikula** [comment]
See [this StackOverflow answer](http://stackoverflow.com/questions/28659716/show-breakpoint-at-line-number-in-richtextfx-codearea/28660913#28660913). Perhaps we should add it to the demos.

**Comment by JordanMartinez** [comment]
Closed via #364.
