### ISSUE TITLE
ALT + Alphanumeric as KeyCombination prints the typed symbol

### ISSUE THREAD

**Issue by arturbosch** [TomasMikula/RichTextFX#366]
I want to implement some shortkeys as ALT+1 to switch to a project explorer, but the 1 is printed everytime I press this combination in a code area. In a JavaFX TextArea this is not the default behaviour.

Is this intentionally or a bug?

**Comment by kuc** [comment]
Duplicate of #350 ?

**Comment by JordanMartinez** [comment]
Aye, seems to be a duplicate. Reopen if you think otherwise.
