### ISSUE TITLE
Can I get a possible caret position, using scene coordinates?

### ISSUE THREAD

**Issue by RodrigoSantiago** [TomasMikula/RichTextFX#368]
I've seen some similar examples but not well explained, and I don't know if it's really possible

**Comment by JordanMartinez** [comment]
If you're using the latest release, use `StyledTextArea#hit(double x, double y)` It'll give you back the position of the caret.

**Comment by JordanMartinez** [comment]
Use `hit(double x, double y)`. [See the javadoc](https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java#L721-L734)
