### ISSUE TITLE
Set text background/text highlight color

### ISSUE THREAD

**Issue by isjns** [TomasMikula/RichTextFX#369]
I'm currently trying to customize the styles in your [JavaKeywordsAsync.java](https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywords.java) example.

Say I want to give keywords a background/highlight color (the use of "highlight" might be a little confusing since the CSS property "-fx-highlight-fill" is actually a property for the selection color in JavaFX, but normally it is a term used for the background color of specific segments of text) by changing the properties in the java-keysword.css, how would I go on doing this? Is it possible?

I've tried using both "-fx-background color" and "-fx-background-fill", but neither seeems to do the trick:

.keyword {
    -fx-fill: purple;
    -fx-font-weight: bold;
    -fx-background-color: blue;
    -fx-background-fill: blue;
}

Thanks in advance!

Best regards
Jonatan

**Comment by TomasMikula** [comment]
Note that JavaFX `Text` [does not support background color](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/doc-files/cssref.html#text). We added it in some recent release as `-rtfx-background-color` (see [the wiki](https://github.com/TomasMikula/RichTextFX/wiki/RichTextFX-CSS-Reference-Guide#the-additional-css-properties-for-textext)).

**Comment by JordanMartinez** [comment]
It seems that this issue was resolved but never closed, so I'm closing it.
If it hasn't been resolved, please reopen.
