### ISSUE TITLE
Get the line where the carret is

### ISSUE THREAD

**Issue by eliottizi** [TomasMikula/RichTextFX#380]
Hi,
I am currently working on a IDE and i need to get the line where the carret is, is there a way to do this in a codearea ?

**Comment by JordanMartinez** [comment]
Try `getCurrentParagraph()`

**Comment by eliottizi** [comment]
It works well ! Thanks for your answer ;)

**Comment by JordanMartinez** [comment]
Great! Can you close this issue?
