### ISSUE TITLE
Paragraph's Line-Spacing CSS doesn't work

### ISSUE THREAD

**Issue by IntelligyScience** [TomasMikula/RichTextFX#382]
Hi,
I am working with the new Version of the Editor 7.2 and try to modify it for using it in scala. 
For the axuliary problem I will open a complete new issue. But for this here is my question, how I can change the line-spacing of paragraphs?

Thank you

André

**Comment by JordanMartinez** [comment]
Use TextFLow's CSS:
````css
    /* when lines are wrapped, the number (double) of pixels between lines */
    -fx-line-spacing: <number>;
````

**Comment by JordanMartinez** [comment]
Also, have you seen the [RichTextFX CSS Reference Guide](https://github.com/TomasMikula/RichTextFX/wiki/RichTextFX-CSS-Reference-Guide)

**Comment by IntelligyScience** [comment]
Hi,
line-spacing had no effect. I will try again and checkout the reference guide again.
Yes I looked at the guide, that was the reason for my question :)
I will show you the code later.

**Comment by JordanMartinez** [comment]
@IntelligyScience Can you give me an update on this?

**Comment by JordanMartinez** [comment]
I can reproduce this bug using this code:
````java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.scene.text.TextFlow;
import javafx.stage.Stage;
import org.fxmisc.flowless.VirtualizedScrollPane;
import org.fxmisc.richtext.InlineCssTextArea;

public class BugDemo extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        InlineCssTextArea area = new InlineCssTextArea("AREA TEXT:\n text here\nadnd\nadfsdf\nadf\ndfasdf\n");
        TextFlow flow = new TextFlow(new Text("TEXTFLOW TEXT:\n"), new Text("some more stuff\n"), new Text("some additional stuff"));

        String css = "-fx-line-spacing: 10px;";
        area.setStyle(css);
        flow.setStyle(css);

        VBox root = new VBox(area, new Text("--------------------"), flow);

        Scene scene = new Scene(root, 500, 500);
        primaryStage.setScene(scene);
        primaryStage.show();
    }

}
````

**Comment by JordanMartinez** [comment]
The Line Spacing CSS doesn't work, but now that I've documented Flowless, I think I understand why.

When the VIrtualFlow's navigator lays out the `ParagraphBox` objects, it does not have any indication of how much space to put in-between those objects. Rather, it lays them out sequentially. So, I think the way to get around this is to add padding to the ParagraphBox objects.

However, when I ran the above demo with a longer line of text on a single line and wrapped the text, the line spacing CSS for TextFlow did not work. I'm not sure if this is supposed to work, but it's something to know.

**Comment by JordanMartinez** [comment]
Thinking about this more, `TextFlow`'s line spacing CSS only applies when it has `Text` objects that contain a newline character in its text. If one wanted to have line spacing apply on a multi-line TextFlow object, _TextFlow doesn't support that_. Since RTFX only uses TextFlow to layout text and custom objects that never have a newline character, applying the CSS will never do anything.

As stated before and in the wiki, to add line spacing between lines, one needs to modify the padding values of ParagraphBox. I've updated the CSS guide to forewarn users about this quirk.
