### ISSUE TITLE
WYSIWYG Document Writer like Office

### ISSUE THREAD

**Issue by IntelligyScience** [TomasMikula/RichTextFX#383]
Hi,
I am trying to build the RichTextFX to a looking like microsoft office or openoffice. With the same functionality. Add pics, special chars an so on.
Now my first question is, how to set the editor to change the font view. I can style a webpreview like as a4 pages with content, but I dont think that this is way here?
André

**Comment by JordanMartinez** [comment]
> I am trying to build the RichTextFX to a looking like microsoft office or openoffice. With the same functionality. Add pics, special chars an so on.

That's possible, but it's going to take a lot more PRs for that to happen. At the same time, I'm wondering how much of what you want fits into the scope of RichTextFX.

> how to set the editor to change the font view. I can style a webpreview like as a4 pages with content, but I dont think that this is way here?

Sorry, but I don't understand what you're asking.

**Comment by IntelligyScience** [comment]
I can change the looking of HTMLEditor or WebView. After the change I have a editor looking like an blank a4 paper.
After looking deeper in code, i think also that this isnt a simple task :(

**Comment by JordanMartinez** [comment]
I'm still not fully understanding what you want to change. After looking at WebView's and HTMLEditor's CSS guide, I'm guessing you want to change how the font is displayed, in which case you should see this project's CSS Reference Guide located in the project's wiki.

> After looking deeper in code, i think also that this isn't a simple task :(

Yes, it won't be easy. #356 would add support for displaying additional items besides rich text (e.g. emoticons, shapes, etc.). Even so, there's been no discussion about how to set up the view (`StyledTextArea`)  in such a way that it only allows so much text before a visual page border appears (e.g. paper-size support and margin support). Besides that, Tomas' original goal was to create this project as a base upon which others could build code editors. So, we'd probably be focusing on other items first (e.g. support for a tablet's popup-keyboard) before getting to that, if at all. As this project becomes more mature, its scope might increase to include that, but Tomas would have to give you that answer, not me.

**Comment by DaveJarvis** [comment]
@IntelligyScience: Take a look at https://github.com/JFormDesigner/markdown-writer-fx

**Comment by JordanMartinez** [comment]
There's also [AsciidocFX](https://github.com/asciidocfx/AsciidocFX)

**Comment by DaveJarvis** [comment]
Nice, @JordanMartinez. Thank you. They support tables.

**Comment by IntelligyScience** [comment]
Thanks!
Great libs
I will dive into the code 👍 

AsciidocFX and mardownwriter are splited in an editor and in one preview. I think this is for persons who works with code day by day no problem. But for a person who is not a "crack" this looks strange. The most likes editor like openoffice/libreoffice or microsoft office. 

I think the idea to create an editor like office is the primary target to me. 
Although I will take a deep look inside

**Comment by JordanMartinez** [comment]
@IntelligyScience Why do you want to create a Java-version of MS Office (as I'm understanding you to say)? Can't people just use MS Office?

**Comment by DaveJarvis** [comment]
Or [OpenOffice](https://www.openoffice.org/), which is free, familiar, and platform independent. Someone might have already written a Markdown plug-in for it.

**Comment by JordanMartinez** [comment]
@DaveJarvis I don't think he (she?) cares whether a Markdown plug-in exists for Open Office. It seems this person only wants a Java version of MS Office.

**Comment by JordanMartinez** [comment]
Closing this issue as it is currently outside the scope of this project.
