### ISSUE TITLE
Demo with Jygments

### ISSUE THREAD

**Issue by daniel6651** [TomasMikula/RichTextFX#387]
Hi

I hacked together an example using Jygments and RichTextFX:
https://github.com/daniel6651/JygPane
And also added some CSS from Pygments I found on various places and tried to adapt them to JavaFX css.

I think adding a more thorough implementation of this would spare many people work if added directly in RichTextFX. Perhaps supporting Sublime Syntax definitions instead of using Jygments?

Cheers,

Daniel

**Comment by JordanMartinez** [comment]
If this is similar to what's already been proposed in #275, please read through that thread. Otherwise, could you clarify how this is different?

**Comment by daniel6651** [comment]
They are a bit similar indeed.
Jygments however have the advantage of being simpler to add upport for a new language.
There is also a ton of languages already supported by pygments that doesn't require much effort to include in jygments.
Ontop of that lots of ready themes from pygments to choose from.
A disadvantage might be that the parsing is somewhat slower than for an ANTLR parser/lexer.
But in short - more bang for the buck.

-Daniel

**Comment by JordanMartinez** [comment]
Makes sense. I'm sure a demo showing a way of adding support for languages that is different from ANTLR would be appreciated.

**Comment by JordanMartinez** [comment]
Closing due to being outside the scope of this project. I've also written an explanation of what "out of the scope of this project" means in [the wiki](https://github.com/TomasMikula/RichTextFX/wiki/General-Guidelines#why-dont-we-add-feature-x-to-richtextfx)
