### ISSUE TITLE
Can RichTextFX be used to select an arbitrary text range for copy/paste operations?

### ISSUE THREAD

**Issue by gbmhunter** [TomasMikula/RichTextFX#388]
I am currently using a stock-standard JavaFX `TextFlow` node for displaying rich text. However, the `TextFlow` node does not currently support selection of text for copy/paste operations.

I was wondering if `RichTextFX` does support this? (I had a quick look through the readme and couldn't find any mention of it).

**Comment by JordanMartinez** [comment]
RichTextFX (via `StyledTextArea` and its flavors) does support selection of text, which can be cut/copied/pasted. Have you seen [ClipboardActions](https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/ClipboardActions.java) which `StyledTextArea` implements?

**Comment by gbmhunter** [comment]
Great that is good news! No I hadn't managed to stumble across that API :-)
