### ISSUE TITLE
Styling the caret (not just colour)

### ISSUE THREAD

**Issue by gbmhunter** [TomasMikula/RichTextFX#397]
When using a `TextFlow` node, I was able to simulate a blinking "terminal" (insert, block-shaped) style caret by adding a `Text` object as follows:

        caretText = new Text("█");
        caretText.setFill(Color.LIME);

        // Add an animation so the caret blinks
        FadeTransition ft = new FadeTransition(Duration.millis(200), caretText);
        ft.setFromValue(1.0);
        ft.setToValue(0.1);
        ft.setCycleCount(Timeline.INDEFINITE);
        ft.setAutoReverse(true);
        ft.play();

        textFlow.getChildren().add(caretText)

This produced the blinking caret as seen in the demo image on the page: [http://mbedded-ninja.github.io/NinjaTerm/](http://mbedded-ninja.github.io/NinjaTerm/)

Is there any way to get the same functionality with RichTextFX?

**Comment by kuc** [comment]
Try setting `-fx-stroke-width` on caret in CSS.

**Comment by gbmhunter** [comment]
Hmmm, that almost works, except it is little high and it collides with the last letter (most likely due to it's center being positioned at the right-most edge of the last letter).

![image](https://cloud.githubusercontent.com/assets/2396869/20394586/58eabdb6-ace0-11e6-9fb6-5865f3dcecb7.png)

**Comment by kuc** [comment]
Yup, there is no checks for caret width:
https://github.com/TomasMikula/RichTextFX/blob/169967a71709c80a36db825cacd617ce9d622ee8/richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java#L83

Allowing custom caret width would be a nice start. Custom caret shapes and positioning (e.g. `_`-shaped caret under current character for overwrite input mode) would be the best option, but that's a lot of work.

**Comment by gbmhunter** [comment]
Hmmm I have had a quick look at the code, what are some good pointers to get started with adding some basic functionality around the caret?

**Comment by JordanMartinez** [comment]
@gbmhunter Are you still interested in taking a look at this?

**Comment by gbmhunter** [comment]
@JordanMartinez Sorry no not anymore. After diving into the source code for a bit I realised it would be a decent amount of work to get up to speed with the architecture and implement the changes, and opted to go for a JavaFX WebView/HTML textarea approach instead.

**Comment by PashaTurok** [comment]
Could anyone say if it is possible to set styles for caret using StyleClassedTextArea in 2022. Same problem - I need something `like` terminal.

**Comment by andy-goryachev-oracle** [comment]
just a suggestion - you could use Text/TextFlow.rangeShape() to draw the "caret", or at least to determine the geometry.
