### ISSUE TITLE
Rich-Text editor demo not working.

### ISSUE THREAD

**Issue by ajitavdutta** [TomasMikula/RichTextFX#399]
I have downloaded the latest demo jar i.e. `richtextfx-demos-fat-0.6.10.jar`. 

All the demos are working except the Rich-Text demo. When I try to run the demo using the command `java -cp richtextfx-demos-fat-0.6.10.jar org.fxmisc.richtext.demo.richtext.RichText` I get the following error:
`Error: Could not find or load main class org.fxmisc.richtext.demo.richtext.RichText`

I am trying to run this demo from a Mac.

**Comment by kuc** [comment]
You are using documentation for version `0.7-M2` or later.
For version `0.6.10` use `org.fxmisc.richtext.demo.RichText`

**Comment by aadrian** [comment]
And the link to screenshot also returns a ```"Not Found"```

**Comment by JordanMartinez** [comment]
@aadrian I've noted the issue in #259's readme updates

**Comment by JordanMartinez** [comment]
Closing as he tried running a demo with the wrong version
