### ISSUE TITLE
Java Keyword Demo

### ISSUE THREAD

**Issue by WinXaito** [TomasMikula/RichTextFX#400]
Hello,

I would like to be able to refresh the "hightlight" when opening the file, but with this code, the "highlight" is only done after editing the file.

```
codeArea.richChanges()
                .filter(ch -> !ch.getInserted().equals(ch.getRemoved()))
                .successionEnds(Duration.ofMillis(100))
                .supplyTask(this::computeHighlightingAsync)
                .awaitLatest(codeArea.richChanges())
                .filterMap(t -> {
                    if(t.isSuccess()) {
                        return Optional.of(t.get());
                    } else {
                        t.getFailure().printStackTrace();
                        return Optional.empty();
                    }
                })
                .subscribe(this::applyHighlighting);
```
This is the code found in the java keyword demo in Async

How can I do this?

Thank you !

[This text has been translated from a translation site, original language: French]

**Comment by JordanMartinez** [comment]
What have you tried so far?

**Comment by WinXaito** [comment]
And well not much, what I would like to call `codeArea.richChanges()` without making a change in codeArea, but I do not know how to do it, you understand?

**Comment by WinXaito** [comment]
Okay, I'm so sorry, I've resolved my problem.. But I don't know why. I have inversed my variable declaration and the problem has been solved.

So I have an another questions, `codeArea.positionCaret(0);` is indicated `@deprecated`, how can I use ? Thanks !

**Comment by JordanMartinez** [comment]
No worries. You should be using `codeArea.moveTo(absolutePosition)` instead or its variant `moveTo(paragraphIndex, linePosition)`

**Comment by WinXaito** [comment]
Okay. Thanks !!
