### ISSUE TITLE
Word break navigation needs option for space skipping

### ISSUE THREAD

**Issue by DaveJarvis** [TomasMikula/RichTextFX#401]
**Replicate**

1. Paste the following pangram into the editor: `Sphinx of black quartz, judge my vow`.
1. Position the caret anywhere along the pangram.
1. Press `Home` to reposition the caret to the beginning of the line.
1. Press `Ctrl+Right Arrow` to move to the end of the current word.

**Expected Results**
Caret moves to the end of the word `Sphinx`, before the word boundary:

`Sphinx| of black...`

**Actual Results**
Caret moves to the start of the next word, `of`, after the word boundary:

`Sphinx |of black...`

**Additional Details**
This is inconsistent with most text editors. When using `Ctrl+Left/Right Arrow` the expected behaviour can be discovered by using a regular input field and moving around the words with `Ctrl` and the arrow keys. Generally speaking, when `Ctrl+Shift` are pressed together for jumping word boundaries, typing an extra space to separate the replaced text from the previous/next word should not be required.

**Comment by JordanMartinez** [comment]
Which version are you using?

**Comment by JordanMartinez** [comment]
This was fixed in 2c3bd1b6feb0d435cb5715862a71a241cda10f32 and this issue is a duplicate of #200. Unfortunately, a release does not yet exists containing the fix.

**Comment by DaveJarvis** [comment]
compile group: 'org.fxmisc.richtext', name: 'richtextfx', version: '0.7-M2'
