### ISSUE TITLE
How to set different styles to words in same paragraph or line ?

### ISSUE THREAD

**Issue by nazmuddin** [TomasMikula/RichTextFX#406]
Hi  , i have two queries.

1. How to set different styles to words in same paragraph or line of `GenericStyledArea` ? I am doing it like this ....

`area.setStyle(area.getText().lastIndexOf(text), area.getText().length(), TextStyle.EMPTY.updateTextColor(color));`

This works only for first word, but when i append the second word with different style like

`area.setStyle(area.getText().lastIndexOf(text), area.getText().length(), TextStyle.EMPTY.updateTextColor(color).updateBold(true);
`
It also changes the style of first text. Now how to do it ?

2. How to add different objects in same GenericStyledArea . What i mean to say is if i define the area like this
`final GenericStyledArea<ParStyle, Either<StyledText<TextStyle>, LinkedImage<TextStyle>>, TextStyle> area `.
I can insert only `LinkedImage` objects into this. But if i have to add lets say an `Text `or `Hyperlink` Object then how to do it. I can manage the hyperlink with styling as you explained in some pull request but if i have to add Hyperlink and Image in area then how to do it ?
Thank you.

**Comment by JordanMartinez** [comment]
For your second question (the code of which has not yet been merged...), you have three basic options.
````java
// Option 1: recursive either
Either<Text<TextStyle>, Either<LinkedImage<TextStyle>, Hyperlink<TextStyle>>>

// Option 2: wrapper type for recursive either
class TripleType extends Either<Text<TextStyle>, Either<LinkedImage<TextStyle>, Hyperlink<TextStyle>>> {
}

// Option 3: custom object
class MyOwnCustomStyleObject {}
````
I don't fully understand what you're asking in your first question

**Comment by nazmuddin** [comment]
@JordanMartinez, 
![action](https://cloud.githubusercontent.com/assets/10191679/21262655/95e33516-c3a3-11e6-9945-3010eb208eba.gif)
I have a method to append text with color 

```
public void insertText(String text, Color color) throws Exception {
        area.appendText(text + "\t");
        area.setStyle(area.getText().lastIndexOf(text), area.getText().length(),
                TextStyle.EMPTY.updateTextColor(color));
    }
```

This works fine when i append a string in `GenericStyledArea`, but when i call it again to append another string in area , it removes the style of first string

I am styling the link with an listener and it works fine and it does not affect other texts in area 

`private final ChangeListener textListener = new ChangeListener<String>() {
        @Override
        public void changed(ObservableValue observable, String oldValue, String newText) {
            String linkRegex = "(https|http|ftp|www|file)\\S*";
            Pattern linkPattern = Pattern.compile(linkRegex);
            Matcher matcher;
            area.clearStyle(0, newText.length());
            matcher = linkPattern.matcher(newText);
            while (matcher.find()) {
                area.setStyle(matcher.start(), matcher.end(), TextStyle.EMPTY
                        .updateTextColor(Color.BLUE)
                        .updateItalic(true)
                        .updateUnderline(true)
                        .updateCursor(Cursor.HAND));
            }
        }
    };`

But why the first method is not working.

**Comment by JordanMartinez** [comment]
@nazmuddin For your first question, why not just use `area.replace`? For example, you could do your `insertText` in this way:
````java
int length = area.getLength();
area.replace(length, length, ReadOnlyStyledDocument.fromString(
    text, // your insertion text
    Collections.emptyList(), // paragraph style
    TextStyle.EMPTY.updateColor(color)) // text style
);
````

**Comment by nazmuddin** [comment]
@JordanMartinez , `ReadOnlyStyleDocument.fromString()` have 4 args. 

```
String str, 
PS paragraphStyle, 
S style, 
TextOps<SEG, S> segmentOps
```
So i am doing it this way...

```
int length = area.getLength();
        area.replace(length, length, ReadOnlyStyledDocument.fromString(
                text,
                ParStyle.EMPTY.updateBackgroundColor(color),  
                TextStyle.EMPTY.updateTextColor(color),styledTextOps._or(linkedImageOps)));
```

`styledTextOps` and `linkedImage`Ops are declared as 

```
private final TextOps<StyledText<TextStyle>, TextStyle> styledTextOps = StyledText.textOps(TextStyle.EMPTY);
    private final LinkedImageOps<TextStyle> linkedImageOps = new LinkedImageOps<>(TextStyle.EMPTY);
```

But it doesn't apply the color to the text. I am using RichText demo codes and adding some method to it for my needs. 

Thank you.

**Comment by nazmuddin** [comment]
@JordanMartinez , As you suggested above for my second query, so i declared the area like this

```
private final GenericStyledArea< ParStyle, Either< StyledText<TextStyle>, Either<LinkedImage<TextStyle>, RichSeparator<TextStyle>>>, TextStyle> area 
            = new GenericStyledArea<ParStyle, Either< StyledText<TextStyle>, Either<LinkedImage<TextStyle>, RichSeparator<TextStyle>>>, TextStyle>(
            ParStyle.EMPTY, 
            (paragraph, style) -> paragraph.setStyle(style.toCss()),
            TextStyle.EMPTY.updateFontSize(12).updateFontFamily("Serif").updateTextColor(Color.BLACK),
            styledTextOps._or(linkedImageOps)._or(richSeparatorOps), 
            seg -> createNode(seg, (text, style) -> text.setStyle(style.toCss(text)))
    );
```

If i use only <> (infer types) it gives me compile time error. But if i add the Parameters to <>, at runtime it gives me this error
 `incompatible types: no instance(s) of type variable(s) R exist so that TextOps<Either<Either<StyledText<TextStyle>,LinkedImage<TextStyle>>,R>,TextStyle> conforms to TextOps<Either<StyledText<TextStyle>,Either<LinkedImage<TextStyle>,RichSeparator<TextStyle>>>,TextStyle>`

Any Help please. Thank you.

**Comment by JordanMartinez** [comment]
@nazmuddin Your issue is probably with this one line:
````java
// creates Either< Either<StyledTextOps, LinkedImageOps>, RichSeparatorOps>, right?
styledTextOps._or(linkedImageOps)._or(richSeparatorOps) 

// try it this way
styledTextOps._or(linkedImageOps._or(richSeparatorOps)) 
````

**Comment by nazmuddin** [comment]
@JordanMartinez , Thank you very much it worked but with a little change, i did it like this 

`styledTextOps._or(linkedImageOps.or(richSeparatorOps))`

May you please suggest me something for my first query, cause your earlier suggestion don't work.
Thanks again.

**Comment by nazmuddin** [comment]
Thank you very much i find the solution for first problem also. I did it like this and it's working now....

```
area.insertText(area.getCaretPosition(),text);
area.setStyle(area.getCurrentParagraph(),TextStyle.EMPTY.updateTextColor(color));
```
