### ISSUE TITLE
Underline is hidden by background shape

### ISSUE THREAD

**Issue by afester** [TomasMikula/RichTextFX#407]
With the following CSS

```
-rtfx-background-color: #dcdcdc;
-rtfx-underline-color: blue;
-rtfx-underline-width: 1px;
```

the blue underline is hidden by the gray background shape.
The underline should be in front of the background shape instead. The following hack in ParagraphText.java fixes this:

```
getChildren().add(/*0,*/ underlineShape);
```

by adding the underline shapes to the end of the ParagraphText's child list. Needs some additional verification before submitting a pull request.

**Comment by TomasMikula** [comment]
Fixed by #408
