### ISSUE TITLE
moveTo() does not change the scroll position anymore

### ISSUE THREAD

**Issue by synth3** [TomasMikula/RichTextFX#414]
Since version 0.7-M3 moveTo() does not scroll the text to the caret position anymore.

How to reproduce:
- Create a CodeArea - for example
- Set text that exceeds one page
- scroll to the top of the area
- call `codeArea.moveTo(codeArea.getText().length() - 1)`
Result: the caret ist placed at the end of the text but the scroll position does not change / tha caret is outside of the text-viewport
Expected Result: The text viewport changes so that the caret is visible (as in 0.7-M2)

**Comment by JordanMartinez** [comment]
Use `requestFollowCaret()` immediately after you write `moveTo`

**Comment by synth3** [comment]
Thanks alot - that did the trick! :)

Before posting this issue I looked at the changes on the releases site. Maybe this major change in behavior should be there too.
