### ISSUE TITLE
RichTextFX controls from FXML?

### ISSUE THREAD

**Issue by robross0606** [TomasMikula/RichTextFX#443]
Is it possible to reference RichTextFX controls from FXML?

**Comment by JordanMartinez** [comment]
I'm not sure, but I'd guess that Tomas wouldn't go out of his way to support it either based on [a similar issue he addressed in Flowless](https://github.com/TomasMikula/Flowless/issues/25)

**Comment by kuc** [comment]
@JordanMartinez But as @hwaite has written, you can use `javafx.beans.NamedArg` instead.

**Comment by JordanMartinez** [comment]
@kuc Thanks for pointing that out. I haven't read through that thread in a long time, but I just remembered it since he mentioned FXML.

**Comment by JordanMartinez** [comment]
Closed by #466.

**Comment by JordanMartinez** [comment]
On second thought, does this mean `GenericEditableStyledDocumentBase` and its subclasses also need to use `NamedArg`?

**Comment by JordanMartinez** [comment]
@robross0606 Let me know if I need to merge #467. I'm not familiar with FXML.

**Comment by JordanMartinez** [comment]
@robross0606 Since I haven't heard back from you (and since no one else has said otherwise), I'm guessing that the `EditableStyledDocument`s don't also need to be FXML ready, and am thus closing this issue.
Reopen if it does and we can fix that issue quickly.
