### ISSUE TITLE
Alternative to setText() method within RichTextFX

### ISSUE THREAD

**Issue by charandeep18** [TomasMikula/RichTextFX#444]
Hi All,

I'm just changing an existing GUI that I have with some of the components available within RichTextFX and have run into a small problem.

Currently, I have a load function that loads text from a text file into an existing text area. I was wondering if there is an alternative to the setText() method available for RichTextFX?

`	    public void OpenFile(ActionEvent event) {
	    	// Setting the filter to show only text files
	    	FileChooser.ExtensionFilter filter = new FileChooser.ExtensionFilter("TXT Files (*.txt)","*.txt");
	    	
	    	FileChooser filechooser = new FileChooser();
	    	filechooser.getExtensionFilters().add(filter);
	    	filechooser.setTitle("Open File");
	   	
	    	File file = filechooser.showOpenDialog(MainStage.getScene().getWindow());
	    	if(file != null){
	    	_readTextArea.SetText(openFile.readFile(file));_ - Causes an undefined error
	    	}
	    }`

**Comment by JordanMartinez** [comment]
Were you looking for `replaceText(String text)`?

**Comment by charandeep18** [comment]
Thanks Jordan, that's done the trick!
