### ISSUE TITLE
Style RichTextFX in TornadoFX with Type Safe CSS

### ISSUE THREAD

**Issue by Morosko** [TomasMikula/RichTextFX#447]
I want to include the RichtTextFX CodeArea into my TornadoFX project. Showing it works fine. But setting a style class with `codeArea.setStyleClass(0, codeArea.length, "command")` doesn't apply my css. 

When I check if the class was set with `println(codeArea.getStyleAtPosition(codeArea.length / 2))` I get the expected output `[command]`.

My CSS class is defined using the TornadoFX Type-Safe CSS functionality:

```Kotlin
class Keywords: Stylesheet() {
    companion object {
        val command by cssclass()
    }

    init {
        command {
            fill = Color.RED
            fontSize = 40.px
            fontWeight = FontWeight.BOLD
        }
    }
}
```

My MainView:

```Kotlin
class MainView: View("Test") {
    var codeArea: CodeArea by singleAssign()
    val controller: mainController by inject()

    override val root = borderpane {
        top = text("Test") {
            addClass(Keywords.command)
        }
        codeArea = CodeArea()
        codeArea.setParagraphGraphicFactory(LineNumberFactory.get(codeArea))

        codeArea.richChanges().subscribe { change ->
            codeArea.setStyleClass(0, codeArea.length, "command")
            println(codeArea.getStyleAtPosition(codeArea.length / 2))
            //codeArea.setStyleSpans(0, controller.computeHighlighting(codeArea.text))
        }
        center = codeArea
    }
}
```

The text `Test` showes up as expected with the red color and huge font size.

Does anybody know, how I can apply the CSS properly?

**Comment by JordanMartinez** [comment]
Shouldn't you be using `Collections.singletonList("command")` instead of `"command"`?

**Comment by JordanMartinez** [comment]
Ah, nevermind. StyleClassedTextArea adds a convenience method...

**Comment by JordanMartinez** [comment]
The issue must be elsewhere as you're using the right method for that.

**Comment by edvin** [comment]
Could it be that' your simply running the View, and not an App that imports the stylesheet? Can you confirm that you're starting your app via something like:

```kotlin
class MyApp : App(MainView::class, Keywords::class)
```

Alternatively, you can manually import the stylesheet in the init block of `MainView`:

```kotlin
init {
    importStylesheet(Keywords::class)
}
```

**Comment by Morosko** [comment]
@JordanMartinez You were right! The problem was with TornadoFX (see other issue). Thank you anyway!
