### ISSUE TITLE
I'm migrating from the JavaFX TextArea to CodeArea...

### ISSUE THREAD

**Issue by ThallyssonKlein** [TomasMikula/RichTextFX#453]
Hi there. I had an interface, and inside it there were a TextArea. So I knew that the CodeArea allows to display the line numbers, so I started the migration from the TextArea to CodeArea. But when I migrated, I noticed that some methods are red underlined. So I would that somebody tell me what's the equivalent methods at CodeArea.

![image](https://cloud.githubusercontent.com/assets/16887598/23951393/afd9f0f4-096c-11e7-8c04-1a98b9e62c48.png)

![image](https://cloud.githubusercontent.com/assets/16887598/23951507/01c450da-096d-11e7-8539-ec99248b0b70.png)

**Comment by JordanMartinez** [comment]
I think you can accomplish that (or at least a close enough equivalent) via the RTFX-specific CSS:
````css
    /* the color of the underline */
    -rtfx-underline-color: <paint>;

    /* the width of the underline */
    -rtfx-underline-width: <size>;

    /* the dash lengths: allows dot/dash style lines */
    -rtfx-underline-dash-array: <size>[ <size>]+;
````
See the [RichTextFX CSS Reference Guide](https://github.com/TomasMikula/RichTextFX/wiki/RichTextFX-CSS-Reference-Guide)

**Comment by ThallyssonKlein** [comment]
No, I think about I can't to explain me correctly. It's Eclipse that's underlining these red methods, and I would to know what's the equivalent methods in CodeArea.

**Comment by JordanMartinez** [comment]
OH! Well when you put it that way... haha

`area.replaceText(String text)` - Note: this will replace the entire area's text with `text`.
`area.replaceText(int from, int to, String text)` - replaces a portion of the text with `text`. Using the same `from` and `to` values will insert text and leaving `text` empty will delete text, though you could just as easily use `deleteText(int from, int to)`.

I believe the other one should be `area.selectedTextProperty()`

**Comment by ThallyssonKlein** [comment]
Only the area.selectedTextProperty() can't be so. It's because the TextArea selectedTextProperty() returns a ReadOnlyStringProperty, so the isNotNull() method exists, but the CodeArea selectTextProperty() returns a ObservableValue<String>, so this method does not exists.

**Comment by JordanMartinez** [comment]
So you want `search` to be visible when the area's selected text has at least one character (selected text always has a value, even an empty string when nothing is selected). In that case, you can do this:
````java
Val<Boolean> hasSelection = Val.create(
    () -> !area.getSelectedText().isEmpty(), 
    area.selectedTextProperty());
search.visibleProperty().bind(hasSelection);
````

**Comment by JordanMartinez** [comment]
> Thank you. I did not know about that structure.

`Val` is from ReactFX, another project Tomas wrote. You can read that code like "When any of the `ObservableValue<T>` objects are invalidated, set the `Val`'s value to whatever is returned by the `Supplier`" (or the Val might only recompute its value when any of the observables are changed, I can't remember at this point).

> I already tried to cast `hasSelection` to `ObservableBooleanValue` but it generate a `ClassCastException`.

Right, because (if I recall correctly) `Val<T>` can only be cast to `ObservableValue<T>` and `ObservableBooleanValue` does not extend `ObservableValue<T>`.

You could use Val to create that binding:
````java
Val<Boolean> selectedPegarAndSelectionNotEmpty = Val.create(
    () -> ListController. /* the rest of your code */ .getSelectedItem().isEqualTo("Pegar habito") && hasSelection.getValue(),
    ListController. /* the rest of your code */ .selectedItemProperty(), hasSelection);
````
There might be a more efficient way to do it, but that should at least get you past this obstacle.

**Comment by ThallyssonKlein** [comment]
> Val is from ReactFX, another project Tomas wrote. You can read that code like "When any of the ObservableValue<T> objects are invalidated, set the Val's value to whatever is returned by the Supplier" (or the Val might only recompute its value when any of the observables are changed, I can't remember at this point).

That's nice. I'll study this project.

> You could use Val to create that binding:

Val<Boolean> selectedPegarAndSelectionNotEmpty = Val.create(
    () -> ListController. /* the rest of your code */ .getSelectedItem().isEqualTo("Pegar habito") && hasSelection.getValue(),
    ListController. /* the rest of your code */ .selectedItemProperty(), hasSelection);

I think about I did something wrong, look:

![captura de tela 30](https://cloud.githubusercontent.com/assets/16887598/23972229/ba78bc78-09af-11e7-8a4a-b16eebb7e407.png)

**Comment by JordanMartinez** [comment]
> I'll study this project.

It'll be worth it.

> I think about I did something wrong

You wrote `selectedItemProperty()`, not `getSelectedItem()`. The first returns the property, the second the actual value currently stored in that property. So, your IDE thinks you're trying to write `BooleanBinding && boolean`, not `boolean && boolean` as you actually mean to write.

**Comment by ThallyssonKlein** [comment]
I'm sorry for my ignorance, but I'm still learning this structure. If I want to make something same it:

![image](https://cloud.githubusercontent.com/assets/16887598/23976341/c5afe8e4-09c5-11e7-8546-64e15bf07445.png)

How I could do it?

**Comment by JordanMartinez** [comment]
As a comment on your code style, store the `selectionModel` because it's unnecessary for you to reference the same object multiple times through that long process you are currently using. It just makes reading the code unnecessarily harder. 
As for your question, if you look at the [wiki page that talks about Val and Var in ReactFX](https://github.com/TomasMikula/ReactFX/wiki/An-Intro-to-Val-and-Var), you'll see that you should use `bind1.orElse(bind2)`. (Also, if you want to learn ReactFX quickly, start with the wiki, then look at the code/javadoc).

Thus, you would write:
```java
// I wasn't sure what `getSelectionModel()` would return, 
//   so I used the type, `SelectionModel`.
SelectionModel sm = ListController.instance.lists.getSelectionModel();
Val<Boolean> bind1 = Val.create(
    () -> sm.getSelectedItem().equals("Pegar...") && hasSelection.getValue(),
    sm.selectedItemProperty(), hasSelection);
Val<Boolean> bind2 = Val.create(
    () -> sm.getSelectedItem().equals("Tarefas...") && hasText.getValue(),
    sm.selectedItemProperty(), hasText);
Services.HAS_MESSAGES.bind(bind1.orElse(bind2));
````

**Comment by ThallyssonKlein** [comment]
Thank you. I already looked for the orElse method, but I don't still read the wiki, so I had not understood. All is work perfectly.

**Comment by JordanMartinez** [comment]
If this issue has been resolved, can you close it @ThallyssonKlein?
