### ISSUE TITLE
Selecting text using keyboard can lock movement

### ISSUE THREAD

**Issue by DaveJarvis** [TomasMikula/RichTextFX#474]
**Replicate**
1. Create two paragraphs that span multiple rows:
    > "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    >
    > "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

1. Move the caret to the beginning of a line near the end of the first paragraph (e.g., `voluptate`).
1. Press `Shift+End` to highlight to the end of the line.
1. Continue to hold `Shift` and tap the `Down` arrow until the caret is positioned at the start of the second line of the second paragraph.
1. Release the `Shift` key.
1. Press the `Up` arrow.

**Expected Results**
The selection clears and the caret moves up to the first line of the second paragraph.

**Actual Results**
The selection clears and the caret does not move. The caret is subsequently locked from navigating up or down using the keyboard.

**Additional Details**
The number of paragraphs is a red herring, but serves to show how the bug can be replicated every time. It can also be replicated using a single paragraph.

**Work Around**
Press `Right` or `Left` arrow to "unlock" the caret.

**Version**

    compile group: 'org.fxmisc.richtext', name: 'richtextfx', version: '1.0.0-SNAPSHOT'
    richtextfx-1.0.0-20170329.013835-146.jar

**Comment by JordanMartinez** [comment]
Is this a duplicate of #423?

**Comment by DaveJarvis** [comment]
Looks the same.
