### ISSUE TITLE
MANIFEST.MF is empty

### ISSUE THREAD

**Issue by veita** [TomasMikula/RichTextFX#476]
The `MANIFEST.MF` in [https://github.com/TomasMikula/RichTextFX/releases/download/v0.6.10/richtextfx-0.6.10.jar](https://github.com/TomasMikula/RichTextFX/releases/download/v0.6.10/richtextfx-0.6.10.jar) is empty.

So all information (e.g. implementation version) that is normally provided via manifest files is missing.

**Comment by JordanMartinez** [comment]
This is true even for the `0.7-M4` release and likely all the releases in-between the two versions. The build file needs to be updated to include that information in the jar.

**Comment by JordanMartinez** [comment]
@veita Can you submit a PR for this?

**Comment by veita** [comment]
Done. See https://github.com/TomasMikula/RichTextFX/pull/517.

**Comment by JordanMartinez** [comment]
Closed by #517
