### ISSUE TITLE
How to use a Text node as a custom object?

### ISSUE THREAD

**Issue by FHannes** [TomasMikula/RichTextFX#477]
There seem to be issues in using a regular Text node as a custom object. The goal was to have a Text node which could be seen as a single object and dynamically change values. The editor does most of this correctly, with the exception of the caret position. In the image below, the text "TextNode" is in the Text node and the "---" is part of the text in the editor (as based on the RichText demo). The caret is in the rightmost position.
![textnode](https://cloud.githubusercontent.com/assets/915760/24557906/ae42ae96-1639-11e7-90c9-dee22abf6397.png)

**Comment by JordanMartinez** [comment]
I think you would need to wrap the Text node in something else (e.g., Region) because the TextFlow that is used to layout the nodes (both text and custom) would interpret that node as part of its text and thus use it to calculate where the caret should be.

**Comment by JordanMartinez** [comment]
Assuming that works, let me know so I can add a small note about that in the wiki page that talks about custom objects.

**Comment by FHannes** [comment]
That does seem to work when wrapped in a Region, though it isn't drawn when there's no other content in the editor. Maybe I'm just doing something wrong though, I'm still fairly new to JavaFX.

**Comment by JordanMartinez** [comment]
> though it isn't drawn when there's no other content in the editor.

Care to elaborate a bit more?

**Comment by JordanMartinez** [comment]
Region might actually be a poor choice because it may not lay out its children according to the right size. As an alternative, you might want to try StackPane.

**Comment by FHannes** [comment]
> Care to elaborate a bit more?
Well, when the editor only has one of the Text objects wrapped in a Region as its content, the Text object either isn't drawn or the text color is white. The caret does show after it in the correct place. Once I type anything, it does draw correctly. But I suspect that may be a result of the layout issue you're referring to.

The region object is like at least twice as tall as the Text object, but the caret only grows to that size when there's other content. So I'm guessing that without any text in the editor, it is drawn but the bottom of the Region at the height of the text in the editor, cutting of the top, which has the wrapped Text object in it. This may be a bug in itself in regards to custom objects.

Here's an example, I hope that clears it up:
![object_wrapped](https://cloud.githubusercontent.com/assets/915760/24591719/5bbfdace-1808-11e7-9920-1656a815ca41.gif)

**Comment by FHannes** [comment]
> you might want to try StackPane

That seems better at first sight, but also comes with an issue of its own:
![object_wrapped2](https://cloud.githubusercontent.com/assets/915760/24591772/733fd37e-1809-11e7-9e98-41d8bd8b63ef.gif)

**Comment by FHannes** [comment]
I have tried wrapping the Text node in a MigPane from the MigLayout library. It has a debug mode which shows the border of the pane itself. It does show that the Pane perfectly wraps around the Text node, yet the behavior doesn't change and the editor still seems to think it is a lot taller than it actually is.
![migpane](https://cloud.githubusercontent.com/assets/915760/24591905/bc2af246-180c-11e7-92ce-e8e10df6bd30.gif)

**Comment by JordanMartinez** [comment]
Have you tried debugging it using [Scenic View](http://fxexperience.com/scenic-view/)?

**Comment by FHannes** [comment]
> Have you tried debugging it using Scenic View?

That produces the same result. The StackPane-wrapped Text node looks fine, but the other text nodes and caret are a lot taller than they should be.

**Comment by JordanMartinez** [comment]
> That produces the same result.

Right, but I was curious to see what the values relating to width/height (min, pref, max width/height) and the compute values (compute pref width, compute region, or whatever those values are. I can't recall them off the top of my head) were.

Do you know if the `Text` node's CSS style class is affecting it? If you adding padding to the area via the `text` style class, this is probably bleeding into your `Text` node as well.

**Comment by FHannes** [comment]
> Right, but I was curious to see what the values relating to width/height (min, pref, max width/height) and the compute values (compute pref width, compute region, or whatever those values are. I can't recall them off the top of my head) were.

I've quickly thrown together this small sample project based on the demo, if you would like to have a look: https://github.com/FHannes/RichTextFX-Sample

**Comment by JordanMartinez** [comment]
Using your sample project, I made the `TextObjNode` extend `TextFlow`, which lays out the Text object properly every time. However, there is still a minor vertical adjustment when a space is added or the caret moves.

**Comment by FHannes** [comment]
>However, there is still a minor vertical adjustment when a space is added or the caret moves.

I'm not seeing that on my end. This is definitely working a lot better with `TextFlow` though.

**Comment by JordanMartinez** [comment]
Hmm. After loading your sample project, when I typed SPACE, the caret's vertical size grew slightly and some space was added (I can't recall whether this was above/below the TextFlow). So, I guess it's only noticeable when the only segment on a paragraph is that custom text node.

Anyways, is this issue resolved now? Can we close it?

**Comment by FHannes** [comment]
> Anyways, is this issue resolved now? Can we close it?

Yeah, thank you.
