### ISSUE TITLE
Eclipse can't import org.fxmisc.richtext.model

### ISSUE THREAD

**Issue by ecarney1** [TomasMikula/RichTextFX#478]
Hi all,

I have added the fat jar file to my build path in eclipse, but I am unable to run the JavaKeywords demo because Eclipse fails to import org.fxmisc.richtext.model for some reason. It says "org.fxmisc.richtext.model cannot be resolved."

It also can't find org.fxmisc.flowless.VirtualizedScrollPane.

Anyone seen any issues like this?

Thanks!

**Comment by kuc** [comment]
Which fat JAR, at what version?

**Comment by ecarney1** [comment]
I'll grab the new release. It looks like this is related to Issue #236 maybe. I can tell you that instead of following the imports in the source at the following link, I had to change to StyleSpans imports to the following. Still having no luck with VirtualizedScrollPane.

import org.fxmisc.richtext.StyleSpans;
import org.fxmisc.richtext.StyleSpansBuilder;

https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywords.java

**Comment by ecarney1** [comment]
It looks like the demos jar is different from the stable release jar. I downloaded the stable release, but only the demos jar has org.fxmisc.richtext.model. I think the demos jar will solve my problem. I will confirm tonight when I get home.

**Comment by kuc** [comment]
Ahh, I see - you used "outdated" fat JAR link from README. I wrote "outdated", because it's linking to the latest "stable" version, that is pretty old (1.5 years).
Demos link is using the lastest tagged version.
Use links from that page: https://github.com/TomasMikula/RichTextFX/releases

**Comment by JordanMartinez** [comment]
I checked the "fat jar" links on the ReadMe. The only one that is "outdated" is the stable release. So, if that's the one you downloaded, that would explain why. All the other links that after their demo's screenshot use the most recent release.

Is this issue now closed?

**Comment by ecarney1** [comment]
Yes, it works now. Issue closed. Thanks!
