### ISSUE TITLE
Can I change the color of the text cursor ?

### ISSUE THREAD

**Issue by YoriChan** [TomasMikula/RichTextFX#480]
@JordanMartinez 
Hello ! Remenber me ?
I changed the CodeArea's background into `black` yesterday.
After that, I found it was difficault to find the text cursor because it was black, too.
Can I change the text cursor's color into `white` or other color ?
Forgive me for my poor CSS plz ...

**Comment by JordanMartinez** [comment]
@YoriChan If you read the [CSS Reference Guide](https://github.com/TomasMikula/RichTextFX/wiki/RichTextFX-CSS-Reference-Guide#the-richtextfx-css-reference-guide), you can style the caret via the style class `caret`.
