### ISSUE TITLE
WrapText + LineNumber, wrong line numbers position

### ISSUE THREAD

**Issue by AlexP11223** [TomasMikula/RichTextFX#488]
When text wrapping and line numbers are enabled, line numbers are displayed incorrectly (which is very confusing and makes them unusable):

![](http://i.imgur.com/HghKg1d.png?1)

They displayed in the center instead of the beginning of the line, like in other text editors. For example Notepad++:

![](http://i.imgur.com/MSgxlGJ.png)

Tried in current master spellchecking demo, as well as in my project with stable and milestone RichTextFX releases.

        StyleClassedTextArea textArea = new StyleClassedTextArea();
        textArea.setWrapText(true);
        textArea.setParagraphGraphicFactory(LineNumberFactory.get(textArea));

**Comment by JordanMartinez** [comment]
Since you can implement your own `ParagraphGraphicFactory`, use `LineNumberFactory` as a base upon which you implement the alignment you want.

**Comment by AlexP11223** [comment]
Isn't it a bug? All editors I know (JetBrains IDEs, Github, ...) use top alignment for line numbers.

**Comment by JordanMartinez** [comment]
Right, but AFAIK, all code editors don't wrap their lines like you are doing.

**Comment by AlexP11223** [comment]
They all have option to wrap, and it can be useful for non-code text files, some config files.

**Comment by JordanMartinez** [comment]
Mm.. makes sense. If we just make LNF layout its children at the top, won't that properly lay out the number regardless of wrapping?

**Comment by AlexP11223** [comment]
Yeah, it should. If I add `lineNo.setAlignment(Pos.TOP_CENTER);` to LNF `apply` it works as expected.

btw I thought that it would be possible to use right alignment and remove zeros added for padding, but looks like in that case width would not be the same :(

![](http://i.imgur.com/jwpwaQ9.png)

**Comment by JordanMartinez** [comment]
Couldn't you use `Pos.TOP_RIGHT`?

**Comment by JordanMartinez** [comment]
Or is that what you meant by "I thought that it would be possible to use right alignment?"

**Comment by AlexP11223** [comment]
Yeah, Currently there is no difference between RIGHT and CENTER because it is padded with 0s.

**Comment by JordanMartinez** [comment]
One other possibly-related problem is if one scrolls a very long document. When only lines 0-9 (single digit) are displayed, the LNF will probably only display just enough horizontal space for those items. As soon as lines 10-99 (double digits) are displayed, the LNF will increase the horizontal space to account for the extra digit. This will cause an unexpected jump in the rendering of the text as it is suddenly rendered farther to the right. Moreover, this jump will occur as soon as lines 100, 1.000, and 10.000 are rendered. 
So, a proper solution should also render the padding correctly no matter how many lines there are in the document, so that the text's horizontal position doesn't jump like that.

**Comment by AlexP11223** [comment]
You mean the jump that I showed on the screenshot above (https://github.com/TomasMikula/RichTextFX/issues/488#issuecomment-293630253)?

**Comment by JordanMartinez** [comment]
Yup! Just pointing out that that is also part of the issue the solution
would need to address.

**Comment by AlexP11223** [comment]
When removed padding with zeros? Then maybe a simple solution would be to pad with spaces, since the line number font is monospace.

**Comment by JordanMartinez** [comment]
> Then maybe a simple solution would be to pad with spaces, since the line number font is monospace.

Good idea. However, shouldn't the LNF still work correctly even when one does not want monospace to be used? Then again, would that go far enough outside the scope of this project that a person who wants that should just implement their own LNF?

**Comment by AlexP11223** [comment]
As far as I can see user cannot change font now, it's just private field.

**Comment by JordanMartinez** [comment]
It's possible by [styling its CSS class `lineno`](https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/LineNumberFactory.java#L60), as that is applied after setting the default font.

**Comment by AlexP11223** [comment]
Ah, yes. But if someone really wants a non-monospace font for line numbers, then they can just set `format` parameter.
Of course it can be done vice versa (leave zeros by default, as it is is now), though I guess in most cases spaces are more convenient than zeros. But I guess this decision is not related to the wrapping problem.

Padding with spaces can be implemented using format like this: `digits -> "%1$" + digits + "s"`.

**Comment by JordanMartinez** [comment]
> But if someone really wants a non-monospace font for line numbers, then they can just set format parameter back to zeros.

And in case they don't, they should just create their own LNF?

> Padding with spaces can be implemented using format like this: digits -> "%1$" + digits + "s".

So, we should change the Pos to be at the top, add another parameter to the base LNF constructor that allows one to pass in the type of formatting to use (spaces or zeros), and update the regular `get(Area)` constructor to use the zeros formatting by default. Does that sound about right?
If that fully addresses this issue, will you submit a PR for it?

**Comment by AlexP11223** [comment]
> add another parameter to the base LNF constructor that allows one to pass in the type of formatting

There is already such constructor. 
https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/LineNumberFactory.java#L35

Or you mean to add another constructor with just one character (string) instead of formatting function?

**Comment by JordanMartinez** [comment]
Closed by #489.

**Comment by JordanMartinez** [comment]
> There is already such constructor.

Sorry, I forgot there was already a constructor for that. It's been a while since I looked at that file. Everything I said before was from memory.
