### ISSUE TITLE
Empty text if I undo continuously

### ISSUE THREAD

**Issue by YoriChan** [TomasMikula/RichTextFX#490]
The UndoManager works well BUT the text will be empty in the end if I undo it continuously ...

I want it to be the initial text, how can I fix it ?

**Comment by kuc** [comment]
Redo, single time?

**Comment by TomasMikula** [comment]
Call `getUndoManager().preventMerge()` after initialization.

**Comment by JordanMartinez** [comment]
Shouldn't it be `getUndoManager().forgetHistory()` after initialization?

**Comment by TomasMikula** [comment]
Ah yes, you are right.

**Comment by YoriChan** [comment]
@TomasMikula @JordanMartinez it works, thanks

**Comment by JordanMartinez** [comment]
Great. Closing
