### ISSUE TITLE
Extend ParagraphGraphicFactory to entire window

### ISSUE THREAD

**Issue by samczsun** [TomasMikula/RichTextFX#491]
I'm not sure if this has already been addressed in a previous issue (I tried searching to no avail), but basically I'm trying to prevent this:

![hi](https://cloud.samczsun.com/b82ea49b76.png)

The CodeArea is allocated the entire right side of the window, but since the code isn't long enough the grey line numbers abruptly cuts off, which is mildly infuriating.

The behaviour I'm trying to replicate is what RSyntaxTextArea does:

![hi again](https://cloud.samczsun.com/331e28b63d.png)

I looked through the code which handles the graphics and to be honest it went a bit over my head. Is there any way that I can get this sort of behaviour using RichTextFX? I'm ok with hacky workarounds if that's what
 it takes 😄.

**Comment by JordanMartinez** [comment]
Sorry, but I'm having trouble understanding what the issue is.

**Comment by TomasMikula** [comment]
You could try to set the background so that the result looks the way you
want.

ParagraphGraphicFactory applies only to paragraphs (lines), an there are no
empty paragraphs inserted to fill the viewport height.

**Comment by samczsun** [comment]
Ah, that's what I was afraid of. I'll just append extra newlines to the text until I familiarize myself with RichTextFX. Thanks!
