### ISSUE TITLE
[0.7-M5] Question: How to retrieve only visible text

### ISSUE THREAD

**Issue by clartaq** [TomasMikula/RichTextFX#492]
Is there any API to retrieve only the text that is visible on-screen along with the indices of it's beginning and end in a larger document?

The use case for this would be editing long documents within a virtual scroll pane. For example, [languagetool](https://languagetool.org) can be used to check for spelling and grammar problems in a doc being edited. Real-time checking works fine for short documents, but analysis becomes too long as the document grows. An alternative would be to do analysis after a period of inactivity, like StackOverflow handles syntax highlighting, for example. But it would be better to be able to do the analysis as the text is entered.

Analyzing only the portion of the document shown on screen would be perfectly acceptable and performant if there were a way to get it programmatically.

**Comment by JordanMartinez** [comment]
At this time, no. This is something that would need to be exposed in Flowless before it could be exposed in RichTextFX. The real solution would be to show which paragraphs are visible (whether partially or not) on top of which you could then implement that feature.

**Comment by JordanMartinez** [comment]
I'm currently adding support for this in #501. Part of me feels like I should expose the `ParagraphBox` as well because then one could do bounds-related things, but I think that would need further discussion from more people.

**Comment by JordanMartinez** [comment]
This is now possible via #501. You can use `getVisibleParagraphs().map(Paragraph::getText)`
