### ISSUE TITLE
(Question) How to work with patterns.

### ISSUE THREAD

**Issue by wesosdqueso** [TomasMikula/RichTextFX#498]
Hi Tomas, this is awesome, i was trying out JavaKeywords demo, but i don't understant how to make it to recognize numbers, adding another String[] KEYWORDS as NUMBERS, didn't work..
`
    private static final String NUMBER_PATTERN = "\\???????\\";`

**Comment by TomasMikula** [comment]
This is a question about regular expressions more than RichTextFX. Anyway, it would be

```java
String NUMBER_PATTERN = "[0-9]+";
```
