### ISSUE TITLE
Calling getCharacterBoundsOnScreen on a paragraph with selection stops the selection being displayed

### ISSUE THREAD

**Issue by twistedsquare** [TomasMikula/RichTextFX#499]
If you have a paragraph that features part of the selection, and you call getCharacterBoundsOnScreen, then the selection will no longer be displayed on that paragraph until you change the selection extent, or scroll the paragraph in and out of view (which resets the display).  Affects 0.7-M5.

I have the fix for this (pull request coming in a sec) but thought I'd record the issue first.

**Comment by JordanMartinez** [comment]
Good catch! (and thanks for opening an issue for it before submitting a PR)

**Comment by JordanMartinez** [comment]
Closed via #500
