### ISSUE TITLE
paragraph-box padding works incorrectly

### ISSUE THREAD

**Issue by AlexP11223** [TomasMikula/RichTextFX#508]
Looks like left padding of `.paragraph-box` adds spacing at the right, and top padding adds spacing at the bottom.

```
.virtualized-scroll-pane .styled-text-area .paragraph-box {
    -fx-padding: 15px 90px 60px 80px;
}
```

(look at horizontal scrollbar)

![](http://i.imgur.com/lEAg9KQ.png)

```
.virtualized-scroll-pane .styled-text-area .paragraph-box {
    -fx-padding: 15px 0 60px 80px;
}
```

![](http://i.imgur.com/jHcqie6.png)

```
.virtualized-scroll-pane .styled-text-area .paragraph-box {
    -fx-padding: 15px 0 60px 0;
}
```

![](http://i.imgur.com/BwYAPOa.png)

```
.virtualized-scroll-pane .styled-text-area .paragraph-box {
    -fx-padding: 15px 0 0 0;
}
```

![](http://i.imgur.com/x52UZh5.png)

**Comment by JordanMartinez** [comment]
Thanks. That does make things clearer now.

**Comment by JordanMartinez** [comment]
Here's the layout code in `ParagraphBox`:
````java
    @Override protected void layoutChildren() {
        Bounds bounds = getLayoutBounds();
        double w = bounds.getWidth();
        double h = bounds.getHeight();
        double graphicWidth = getGraphicPrefWidth();

        text.resizeRelocate(graphicWidth, 0, w - graphicWidth, h);

        graphic.ifPresent(g -> g.resizeRelocate(graphicOffset.get(), 0, graphicWidth, h));
    }
````
However, if we fix the left padding issue, there's nothing clipping the line. For example, given a padding of 30px where the mouse marks where the padding ends...

...and content is scrolled completely to the left
![untitled window_006](https://cloud.githubusercontent.com/assets/8413037/26525856/28637078-4319-11e7-8070-cdb1ca851dcf.png)

...and content is scrolled completely to the right
![untitled window_007](https://cloud.githubusercontent.com/assets/8413037/26525857/2e4f7ce8-4319-11e7-81e3-5044bcf22a55.png)

**Comment by JordanMartinez** [comment]
Accounting for padding here will also affect any `hit`-related code

**Comment by JordanMartinez** [comment]
@AlexP11223 Adding padding to this can be done, but do you expect the padding to cover the text when one scrolls to the right?

**Comment by AlexP11223** [comment]
I don't know, I solved my original problem using different approach (adding insets handling to the pane, #507). And for that problem I actually wanted to add padding for paragraph + line numbers, not just for text.

**Comment by JordanMartinez** [comment]
Ah... it seems I misread you then. So you want to add padding to the box itself (which currently doesn't work for top/left padding values), not necessarily the text itself, right?

**Comment by AlexP11223** [comment]
Yeah. But I don't know if it would be correct behavior for this padding, and seems like my problem can be solved without it.

**Comment by JordanMartinez** [comment]
> I don't know if it would be correct behavior for this padding

What do you mean?

**Comment by AlexP11223** [comment]
That I don't know how it supposed to work by design.
For my original problem pane padding is probably better solution than paragraph padding.

**Comment by JordanMartinez** [comment]
Ok, so the original issue you raised is, you think, better resolved by the other approach, correct? 

Still, I think the desired functionality here should be implemented. Someone else might want to use it for various things.
