### ISSUE TITLE
Support for Editor Configuration

### ISSUE THREAD

**Issue by yemikudaisi** [TomasMikula/RichTextFX#521]
In one of my working projects built on RichTextFX, I use a workflow that enables me to specify the code area language like this
```
CodeEditorConfiguration cfg = new XmlCodeEditorConfiguration();
 CodeEditor = new CodeEditor(cfg, sampleCode);
```

Also, each configuration get's to specify it's style within the class (with the use of a `URLStreamHandlerFactory` ) thus making each configuration class more compact and self dependent. So, I'm wondering if the idea is worth a pull request or if RichTextFX would be better without it (as the above example tends to be gearing towards a code editor rather than a control that an editor can be built upon ). Additionally, I'm also considering specifying  line number functionality from the editor configuration.

**Comment by JordanMartinez** [comment]
Thanks for the idea, but I'd say it's just far enough out of the scope of this project.
