### ISSUE TITLE
Feature: Add API for Paragraph's Bounds

### ISSUE THREAD

**Issue by JordanMartinez** [TomasMikula/RichTextFX#537]
To help implement #77 and #405, there should be some API to calculate a given paragraph's bounds by its index (the index in the list of visible paragraphs and all paragraphs). For example
````java
public final Optional<Bounds> paragraphBounds(int parIndex);
public final Optional<Bounds> visibleParagraphBounds(int parIndex);
````

**Comment by maPaydar** [comment]
Hi.
when you wanna implement that ?
i need some widget that show styled texts and emojis and be selecteble. some thing like generic styled area node.
but i want the height of node wrap height of text.

thanks you.

**Comment by dlemmermann** [comment]
Yes, this would be very critical for my current project, too.
