### ISSUE TITLE
How to reposition the caret?

### ISSUE THREAD

**Issue by wesosdqueso** [TomasMikula/RichTextFX#544]
Just upgraded from 0.7-M1 to 0.7 M5. And positionCaret(int) method is no longer avaiable. It was deprecated in the previous version and now it's completely gone.

**Comment by JordanMartinez** [comment]
It is named `displaceCaret` now so that the method name isn't confused with `moveTo`

**Comment by wesosdqueso** [comment]
I having a little issue setting default font-family/color on none PATTERN words in codeArea. Font size works fine, which was implemented via StyleClass,

```
.codearea{
	-fx-font-size: 15px;/*ok*/
	-fx-font-family: "consolas";/*doesn't apply*/
    -fx-fill: #049bce;/*neither this */
}
```
codeArea.getStyleClass().add("codearea");
