### ISSUE TITLE
Error importing cloned project into Eclipse

### ISSUE THREAD

**Issue by afla** [TomasMikula/RichTextFX#545]
Can anyone help me import this project into Eclipse? I would like to debug through the demos to understand them better.

This is the error I get when I try to import a Gradle project, pointing to a location where I previously cloned the Git repository.

Please take into consideration that I have zero knowledge about Gradle. I mean I was to build some example projects with Gradle in Eclipse, but I have not created any Gradle setup from scratch and I have no idea how it actually works.

![capture](https://user-images.githubusercontent.com/1530640/28359762-9fe51718-6c73-11e7-909f-9d0069d59254.PNG)

**Comment by JordanMartinez** [comment]
Sorry @afla, but I use IntelliJ. Since this deals more with Eclipse, I'd ask them. 

You could always try deleting the project and reimporting it again to see if that helps.

Regardless, I'm closing this issue since it's unrelated to this project. Try StackOverflow instead.
