### ISSUE TITLE
Looking for updated demo on creating hyperlink

### ISSUE THREAD

**Issue by stevedefazio** [TomasMikula/RichTextFX#546]
I tried to create a hyperlink via the demo code in #283 , however when I copied the code I got a Cannot Infer Type Arguments on the StyledTextArea. I'm wondering if the way to do this has changed in the past year.

I'm trying to do much the same thing. When the user types something that looks like a link, I want it to be ctrl-clickable.

PS Big fan of this library. I don't know how a rich text editor isn't included in JavaFX out of the box.

**Comment by JordanMartinez** [comment]
Do you simply want the hyperlink to appear as a hyperlink? Or do you want clicking it to also open a web browser to that specific link? The former is easier as you can just extend `StyledTextArea`. If you want the latter, you'll need to implement `Hyperlink` as a custom object. Additional modifications may be necessary.

**Comment by stevedefazio** [comment]
It would need to be clickable., otherwise yes it would be a simple thing to do with css.

**Comment by JordanMartinez** [comment]
Read through [this wiki page](https://github.com/TomasMikula/RichTextFX/wiki/Implementing-custom-objects) if you haven't already, and let me know what problems you encounter. Despite custom object support being implemented, I'm not sure who's actively using that support, nor what issues they have run into. Your situation would provide a good case to improve that process.

**Comment by JordanMartinez** [comment]
Also, the RichText demo uses custom objects to display images in the text. I'd look at that to get an initial idea for how to implement your custom area.

**Comment by stevedefazio** [comment]
Is there javadoc available? I'm looking at the RichTextFX demo, but the GenericStyledArea in there is created with more code than I'm comfortable blindly copy+pasting. I'm also thinking it might be simpler to do a workaround, where a keyboard shortcut takes me to the link the cursor is on. That code is pretty clear in the demos.

**Comment by JordanMartinez** [comment]
Did you figure it out?

**Comment by stevedefazio** [comment]
I didn't figure out the hyperlink. Instead, when I hit a key combo it
treats the "word" the cursor is on as a url, and opens it. It's a
workaround, but ultimately gets me to the same place.

**Comment by JordanMartinez** [comment]
Hmmm... I think we should provide a demo that does this since the `RichTextDemo` is a bit too cluttered and since it's bee brought up multiple times...

**Comment by JordanMartinez** [comment]
See #550.
