### ISSUE TITLE
Improve selection display

### ISSUE THREAD

**Issue by RodrigoSantiago** [TomasMikula/RichTextFX#549]
When there is a selection with empty lines, the result may confuse the user :
![img1](https://user-images.githubusercontent.com/11353496/28756100-4425b85a-753e-11e7-936e-339eaa715407.png)

Some text editors use half-characters (github web editor) :
![img2](https://user-images.githubusercontent.com/11353496/28756160-51114452-753f-11e7-8ab1-e2163ecf908e.png)

And others fill the entire line (intellj) :

![intellj](https://user-images.githubusercontent.com/11353496/28756175-87f192c4-753f-11e7-96b0-1c7605a2c9ff.png)

**Comment by JordanMartinez** [comment]
I agree. I've actually been annoyed by that myself but never thought too much about it.

Off the top of my head, I think the half-character approach would be easiest.

**Comment by JordanMartinez** [comment]
After having a look, this would require more-than-minor refactoring

**Comment by JordanMartinez** [comment]
Personally, I like the full-line approach best.
