### ISSUE TITLE
Calculate highlighting of brackets

### ISSUE THREAD

**Issue by stevedefazio** [TomasMikula/RichTextFX#566]
I'm trying to calculate highlighting for brackets. And while I think the algorithm is right, I am not sure I'm using the right method to set the style. What I'm trying to do is say "Set the style for the characters from point A to point B", but codeArea.setStyle doesn't seem to be doing anything.

````java
codeArea.caretPositionProperty()
    .addListener((observable, oldValue, newValue) -> {
        if (codeArea.getText(newValue - 1, newValue).equals("[")) {
            int match = computeHighlightingBrackets(configCode.getText(), newValue - 1);
            System.out.println(match);
            codeArea.setStyle(match-1, match, 
                Arrays.asList("-fx-font-family: consolas","-fx-font-size: 30pt;"));
        }
    });

int computeHighlightingBrackets(String text, int start){
	int openPos = start;
		int closePos = openPos;
		int counter = 1;
		while (counter > 0) {
			char c = text.charAt(++closePos);
			if (c == '[') {
				counter++;
			} else if (c == ']') {
				counter--;
			}
		}
	return closePos;
}
````

**Comment by JordanMartinez** [comment]
Your algorithm is right. However, CodeArea's style type is `Collection<String>>`
In other words, it's expecting you to define a style class in an external CSS file. For example
````
src/
    main/
        java/
            resources/
                custom.css
````
where `custom.css` defines brackets as a style class:
````css
.code-area-bracket {
  -fx-font-family: consolas;
  -fx-font-size: 30pt;
}
````
then you'd use
````java
codeArea.getStyleSheets().add(YourCustomArea.class.getResource("custom.css").toExternalForm());

// ...
codeArea.setStyleClass(match-1, match, "code-area-bracket");
````

**Comment by stevedefazio** [comment]
*facepalm* that makes sense! Thank you!

**Comment by stevedefazio** [comment]
I had been looking at this example, https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/FontSizeSwitcher.java

Am I right then that the difference is that setStyle(...) gets passed a hardcoded value while setStyleClass(...) uses css?

**Comment by JordanMartinez** [comment]
[`setStyleClass` is a convenience method that `StyleClassTextArea` adds](https://github.com/TomasMikula/RichTextFX/blob/b5a167d2e9c9425bc40200efa2f6593c6398c365/richtextfx/src/main/java/org/fxmisc/richtext/StyleClassedTextArea.java#L45-L50) so that one doesn't have to write boilerplate.

**Comment by JordanMartinez** [comment]
Closing since the original issue has been addressed. Feel free to keep asking questions though.
