### ISSUE TITLE
Show caret inmediately after change

### ISSUE THREAD

**Issue by Starkus** [TomasMikula/RichTextFX#580]
When moving the caret through the lines of text it's hard to keep track of it, since it's constantly blinking. It should reset the blinking timer or whatever when moving it or after any change on the control.

**Comment by JordanMartinez** [comment]
Which version are you using? I believe this was already reported (to a degree) in #189 and fixed later on. You can see the current caret code for handling the caret blinking [here](https://github.com/TomasMikula/RichTextFX/blob/21bded51ac7e37a2dc80aaf3938d542b4cc453e0/richtextfx/src/main/java/org/fxmisc/richtext/CaretImpl.java#L268-L275). The `caretDirty` stream is passed in as the `restartImpulse` stream.

**Comment by Starkus** [comment]
Nvm I was using the stable version on the readme. I built the lastest and it works wonders now.
