### ISSUE TITLE
Reassignment of the key button

### ISSUE THREAD

**Issue by MrChebik** [TomasMikula/RichTextFX#591]
I have an `CodeArea`, and this event:
```
this.setOnKeyTyped(event -> {
    if (event.getCharacter().equals("\t")) {
        this.insertText(this.getCaretPosition(), "    ");
        event.consume();
    }
});
```

I want to change width of tab key, but `event.consume()` does not work and I get previous `\t` and four spaces after `\t`:
```
|
_______    |
```

|  key  |   explanation    |
|:-----:|:----------------:|
|   I   | caret            |
| _     | width of tab     |
| space | my inserted text |

**Comment by JordanMartinez** [comment]
Have you read `GenericStyledArea`'s class' javadoc? I believe it specifies that you aren't supposed to use `setOn[Event](handler)`, but rather the code pattern found in [Override Behavior Demo](https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/OverrideBehaviorDemo.java)

**Comment by MrChebik** [comment]
Thank you!
