### ISSUE TITLE
Paragraph-level styles

### ISSUE THREAD

**Issue by TomasMikula** [TomasMikula/RichTextFX#6]
To support rich-text editors, it should be possible to assign paragraph-level styles, such as alignment, heading, ...

**Comment by TomasMikula** [comment]
Currently, `StyledTextArea` is parameterized by a type parameter `S`, which represents the type of style information that can be applied to text. In concrete subclass, `S` can be a list of style classes (as in `StyleClassedTextArea`), a CSS string (as in `InlineCSSTextArea`), or any user defined type (such as `StyleInfo` in the RichText demo application).

The [StyledTextArea constructor](https://github.com/TomasMikula/RichTextFX/blob/07fc7a165bc9ebdbb262cdbad88ff4c48562eebe/richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java#L388) takes the initial (default) style and a that is capable of applying that opaque style object to a `Text` node.

To add support for paragraph-level styles, we need to add a second type parameter `P` to `StyledTextArea` that will represent the type of style that can be applied to whole paragraphs. The constructor will then accept two additional arguments: the default paragraph style and a function capable of applying an object of type `P` to a `TextFlow` (`TextFlow` is the visual rendering of a paragraph.)

The addition of the second type parameter will propagate down to `StyledDocument` and `Paragraph` as well.

The change is not going to be backwards compatible. However, the users of some concrete subclasses such as `StyleClassedTextArea` may not be impacted too much.

**Comment by TomasMikula** [comment]
So this is now mostly implemented. Among the remaining things to do is to support copying to the clipboard including paragraph style.

**Comment by JordanMartinez** [comment]
I was testing out the demo, and it seems another thing to support is the UndoManager. As of now, it  doesn't undo/redo the paragraph's style.

After the program started, I typed some text, and then changed the line's background color. After undoing my action, the text was deleted but the line's background color remained the same. When I redo my action, the text reappears but the line's background color returns to the initial white color.

The same basic thing happened with the paragraph's alignment values. When I change the alignment to Center and then click Undo, the text is deleted but the alignment remains at Center. When I redo, the text reappears but the text is aligned to the left _despite the Alignment Center button still appearing to be pressed._

**Comment by TomasMikula** [comment]
Copy&Paste is now fixed in master.

**Comment by TomasMikula** [comment]
Undo/Redo now seems to work, too.
