### ISSUE TITLE
Suggestion for snippets

### ISSUE THREAD

**Issue by ghost** [TomasMikula/RichTextFX#63]
Hi Tomas, 
I would like to suggest adding API to create snippets. the idea is that those snippets would know if they are being selected, hovered over, etc. and a text area would know these snippets' locations, their style, etc. and probably have a property to report on which, if any, snippet is being clicked inside of or selected.

i implemented a very sketchy version, which half-works for the purpose of my project, but i thought such element type would be cool to have i richtextfx.

thanks ! 
Maher

**Comment by RobertBColton** [comment]
I'd just like to mention here for reference, I don't know if it should be a separate ticket or not but, bookmarks. The snippets could also serve as bookmarks to jump to specific identfiers/etc. Though that may be beyond the scope of RTFX.

**Comment by JordanMartinez** [comment]
This is another issue that I believe should now be possible to implement on top of RTFX due to the added custom object support. Thus, I'm closing this. 
Please reopen if you think otherwise.
