### ISSUE TITLE
Text overlapping when single line is divided into several display lines

### ISSUE THREAD

**Issue by janghyunq** [TomasMikula/RichTextFX#95]
Hi Tomas.
In CodeArea, if a long single line displays through multiple display lines, sometimes the texts are overlapped and distorted. I made a video clip. Please check this out.

http://www.youtube.com/watch?v=OQwyhhaPYz0&feature=youtu.be

**Comment by TomasMikula** [comment]
Hi, I know this is way overdue, but see the progress at #88.

**Comment by TomasMikula** [comment]
This seems fixed in version 0.6, but I would be happy if you could test it with your code.
