### ISSUE TITLE
Suggestion: Background color controls

### ISSUE THREAD

**Issue by melkhaldi** [TomasMikula/RichTextFX#96]
Hi Tomas, Would it be possible to specify background color(s) for parts of code area by line numbers? 

For example area.setBackground(color) : would color all, or setBackground(color, start # , end #) where end is exclusive. I am trying to find a way to achieve something like this (photoshoped-image):

![example](https://cloud.githubusercontent.com/assets/5727365/5040598/d5289c18-6b65-11e4-9d72-599d2284e564.PNG)

Thanks,
Maher

**Comment by TomasMikula** [comment]
This is now possible with the latest SNAPSHOT release. In `InlineCssTextArea`, you can use

```java
area.setParagraphStyle(7, "-fx-background-color: gray;");
```
