### ISSUE TITLE
selectRange() is very slow

### ISSUE THREAD

**Issue by jntrb** [TomasMikula/RichTextFX#99]
Since there is no way of scrolling at the moment (see bug #98), I am using a workaround os selectRange(index,index). However, this is very slow.

In a 4800 lines file with 3 different styles per line, it takes more than 6 seconds to perform the operation on a Intel core i7 machine.

		long nanoTime = System.nanoTime();
		codeArea.selectRange(codeArea.getText().length(), codeArea.getText().length());
		System.out.println(System.nanoTime() - nanoTime);

**Comment by TomasMikula** [comment]
This is fixed in version 0.6.2. Sorry it took so long.

**Comment by jntrb** [comment]
Thanks for fixing. The links on the main page are broken.
Demo link on main page: https://github.com/TomasMikula/RichTextFX/releases/download/v0.6.2/richtextfx-demos-fat-0.6.2.jar
Correct demo link: https://github.com/TomasMikula/RichTextFX/releases/download/v0.6.2.1/richtextfx-demos-fat-0.6.2.jar
Download link: https://github.com/TomasMikula/RichTextFX/releases/download/v0.6.2/richtextfx-0.6.2.jar
Correct download link: https://github.com/TomasMikula/RichTextFX/releases/download/v0.6.2.1/richtextfx-0.6.2.jar

**Comment by TomasMikula** [comment]
Thanks, I fixed the links.
